
source $ad_hdl_dir/library/jesd204/scripts/jesd204.tcl

# transceiver core

ad_xcvr_parameter number_of_lanes 8
ad_xcvr_parameter rx_bufg_enable 1
ad_xcvr_parameter rx_lane_rate {6.250 Gbps}
ad_xcvr_parameter rx_ref_clk_frequency {625.000 MHz}
ad_xcvr_instance axi_ad9625_0_xcvr

ad_xcvr_parameter number_of_lanes 8
ad_xcvr_parameter rx_bufg_enable 0
ad_xcvr_parameter rx_lane_rate {6.250 Gbps}
ad_xcvr_parameter rx_ref_clk_frequency {625.000 MHz}
ad_xcvr_instance axi_ad9625_1_xcvr
ad_connect axi_ad9625_0_xcvr_rx_core_clk axi_ad9625_1_xcvr/rx_core_clk

# adc peripherals (jesd)

adi_axi_jesd204_rx_create axi_ad9625_0_jesd 8
ad_connect axi_fmcadc5_sync_rx_sysref axi_ad9625_0_jesd/sysref
ad_connect axi_fmcadc5_sync_rx_sync_0 axi_ad9625_0_jesd/sync
ad_connect axi_ad9625_0_xcvr_rx_core_clk axi_ad9625_0_jesd/device_clk
ad_connect axi_ad9625_0_jesd/phy_en_char_align axi_ad9625_0_xcvr/rxencommaalign

adi_axi_jesd204_rx_create axi_ad9625_1_jesd 8
ad_connect axi_fmcadc5_sync_rx_sysref axi_ad9625_1_jesd/sysref
ad_connect axi_fmcadc5_sync_rx_sync_1 axi_ad9625_1_jesd/sync
ad_connect axi_ad9625_0_xcvr_rx_core_clk axi_ad9625_1_jesd/device_clk
ad_connect axi_ad9625_1_jesd/phy_en_char_align axi_ad9625_1_xcvr/rxencommaalign

# adc peripherals (ad9625-core)

ad_ip_instance axi_ad9625 axi_ad9625_0_core
ad_ip_parameter axi_ad9625_0_core CONFIG.ID 0
ad_connect axi_ad9625_0_xcvr_rx_core_clk axi_ad9625_0_core/rx_clk
ad_connect axi_ad9625_0_jesd/rx_sof axi_ad9625_0_core/rx_sof
ad_connect axi_ad9625_0_jesd/rx_data_tdata axi_ad9625_0_core/rx_data
ad_connect axi_ad9625_0_core/adc_raddr_out axi_ad9625_0_core/adc_raddr_in

ad_ip_instance axi_ad9625 axi_ad9625_1_core
ad_ip_parameter axi_ad9625_1_core CONFIG.ID 1
ad_connect axi_ad9625_0_xcvr_rx_core_clk axi_ad9625_1_core/rx_clk
ad_connect axi_ad9625_1_jesd/rx_sof axi_ad9625_1_core/rx_sof
ad_connect axi_ad9625_1_jesd/rx_data_tdata axi_ad9625_1_core/rx_data
ad_connect axi_ad9625_0_core/adc_raddr_out axi_ad9625_1_core/adc_raddr_in

# adc peripherals (fmcadc5-sync, linux helper only - optional otherwise)

ad_ip_instance axi_fmcadc5_sync axi_fmcadc5_sync
ad_connect sys_cpu_reset axi_fmcadc5_sync/delay_rst
ad_connect sys_200m_clk axi_fmcadc5_sync/delay_clk
create_bd_port -dir O rx_sysref_p
create_bd_port -dir O rx_sysref_n
ad_connect axi_fmcadc5_sync/rx_sysref_p rx_sysref_p
ad_connect axi_fmcadc5_sync/rx_sysref_n rx_sysref_n
ad_connect axi_fmcadc5_sync_rx_sysref axi_fmcadc5_sync/rx_sysref
create_bd_port -dir O rx_sync_0_p
create_bd_port -dir O rx_sync_0_n
ad_connect axi_fmcadc5_sync/rx_sync_0_p rx_sync_0_p
ad_connect axi_fmcadc5_sync/rx_sync_0_n rx_sync_0_n
ad_connect axi_fmcadc5_sync_rx_sync_0 axi_fmcadc5_sync/rx_sync_0
create_bd_port -dir O rx_sync_1_p
create_bd_port -dir O rx_sync_1_n
ad_connect axi_fmcadc5_sync/rx_sync_1_p rx_sync_1_p
ad_connect axi_fmcadc5_sync/rx_sync_1_n rx_sync_1_n
ad_connect axi_fmcadc5_sync_rx_sync_1 axi_fmcadc5_sync/rx_sync_1
create_bd_port -dir O psync
create_bd_port -dir O vcal
ad_connect axi_fmcadc5_sync/psync psync
ad_connect axi_fmcadc5_sync/vcal vcal
ad_disconnect spi_csn_o axi_spi/ss_o
ad_disconnect spi_csn_i axi_spi/ss_i
ad_connect axi_spi/ss_i GND
ad_disconnect spi_clk_i axi_spi/sck_i
ad_connect axi_spi/sck_i GND
ad_disconnect spi_clk_o axi_spi/sck_o
ad_disconnect spi_sdo_i axi_spi/io0_i
ad_connect axi_spi/io0_i GND
ad_disconnect spi_sdo_o axi_spi/io0_o
ad_disconnect spi_sdi_i axi_spi/io1_i
ad_connect axi_spi/ss_o axi_fmcadc5_sync/spi_csn_o
ad_connect axi_spi/sck_o axi_fmcadc5_sync/spi_clk_o
ad_connect axi_spi/io0_o axi_fmcadc5_sync/spi_sdo_o
create_bd_port -dir O -from 7 -to 0 spi_csn
create_bd_port -dir O spi_clk
create_bd_port -dir O spi_mosi
create_bd_port -dir I spi_miso
ad_connect axi_fmcadc5_sync/spi_csn spi_csn
ad_connect axi_fmcadc5_sync/spi_clk spi_clk
ad_connect axi_fmcadc5_sync/spi_mosi spi_mosi
ad_connect spi_miso axi_fmcadc5_sync/spi_miso
ad_connect spi_miso axi_spi/io1_i
ad_connect axi_ad9625_0_xcvr_rx_core_clk axi_fmcadc5_sync/rx_clk
ad_connect axi_ad9625_0_core/adc_enable axi_fmcadc5_sync/rx_enable_0
ad_connect axi_ad9625_0_core/adc_data axi_fmcadc5_sync/rx_data_0
ad_connect axi_ad9625_1_core/adc_enable axi_fmcadc5_sync/rx_enable_1
ad_connect axi_ad9625_1_core/adc_data axi_fmcadc5_sync/rx_data_1

# adc peripherals (fifo, see system_bd.tcl)

ad_connect axi_ad9625_0_xcvr_rx_core_clk axi_ad9625_fifo/adc_clk
ad_connect axi_fmcadc5_sync/rx_enable axi_ad9625_fifo/adc_wr
ad_connect axi_fmcadc5_sync/rx_data axi_ad9625_fifo/adc_wdata
ad_connect axi_ad9625_fifo/adc_wovf axi_ad9625_0_core/adc_dovf
ad_connect axi_ad9625_fifo/adc_wovf axi_ad9625_1_core/adc_dovf
ad_connect sys_cpu_clk axi_ad9625_fifo/dma_clk
ad_connect axi_ad9625_fifo/adc_rst GND

# adc peripherals (dma)

ad_ip_instance axi_dmac axi_ad9625_dma
ad_ip_parameter axi_ad9625_dma CONFIG.DMA_TYPE_SRC 1
ad_ip_parameter axi_ad9625_dma CONFIG.DMA_TYPE_DEST 0
ad_ip_parameter axi_ad9625_dma CONFIG.ID 0
ad_ip_parameter axi_ad9625_dma CONFIG.AXI_SLICE_SRC 0
ad_ip_parameter axi_ad9625_dma CONFIG.AXI_SLICE_DEST 0
ad_ip_parameter axi_ad9625_dma CONFIG.SYNC_TRANSFER_START 0
ad_ip_parameter axi_ad9625_dma CONFIG.DMA_LENGTH_WIDTH 24
ad_ip_parameter axi_ad9625_dma CONFIG.DMA_2D_TRANSFER 0
ad_ip_parameter axi_ad9625_dma CONFIG.CYCLIC 0
ad_ip_parameter axi_ad9625_dma CONFIG.DMA_DATA_WIDTH_SRC 64
ad_ip_parameter axi_ad9625_dma CONFIG.DMA_DATA_WIDTH_DEST 64
ad_connect sys_cpu_clk axi_ad9625_dma/s_axis_aclk
ad_connect sys_cpu_resetn axi_ad9625_dma/m_dest_axi_aresetn
ad_connect axi_ad9625_fifo/dma_wr axi_ad9625_dma/s_axis_valid
ad_connect axi_ad9625_fifo/dma_wdata axi_ad9625_dma/s_axis_data
ad_connect axi_ad9625_dma/s_axis_ready axi_ad9625_fifo/dma_wready
ad_connect axi_ad9625_dma/s_axis_xfer_req axi_ad9625_fifo/dma_xfer_req

# interconnect (cpu)

ad_cpu_interconnect 0x44a60000 axi_ad9625_0_xcvr
ad_cpu_interconnect 0x44b60000 axi_ad9625_1_xcvr
ad_cpu_interconnect 0x44a90000 axi_ad9625_0_jesd
ad_cpu_interconnect 0x44b90000 axi_ad9625_1_jesd
ad_cpu_interconnect 0x44a10000 axi_ad9625_0_core
ad_cpu_interconnect 0x44b10000 axi_ad9625_1_core
ad_cpu_interconnect 0x44a20000 axi_fmcadc5_sync
ad_cpu_interconnect 0x7c420000 axi_ad9625_dma

# interconnect (adc)

ad_mem_hp0_interconnect sys_cpu_clk axi_ad9625_dma/m_dest_axi

# interrupts

ad_cpu_interrupt ps-12 mb-12 axi_ad9625_dma/irq

