###############################################################################
## Copyright (C) 2020-2023, 2026 Analog Devices, Inc. All rights reserved.
### SPDX short identifier: ADIBSD
###############################################################################

set_property PACKAGE_PIN C31 [get_ports {ddr4_rtl_0_adr[0]}]
set_property PACKAGE_PIN B31 [get_ports {ddr4_rtl_0_adr[1]}]
set_property PACKAGE_PIN A27 [get_ports {ddr4_rtl_0_adr[2]}]
set_property PACKAGE_PIN A28 [get_ports {ddr4_rtl_0_adr[3]}]
set_property PACKAGE_PIN A30 [get_ports {ddr4_rtl_0_adr[4]}]
set_property PACKAGE_PIN A31 [get_ports {ddr4_rtl_0_adr[5]}]
set_property PACKAGE_PIN C28 [get_ports {ddr4_rtl_0_adr[6]}]
set_property PACKAGE_PIN C29 [get_ports {ddr4_rtl_0_adr[7]}]
set_property PACKAGE_PIN B29 [get_ports {ddr4_rtl_0_adr[8]}]
set_property PACKAGE_PIN B30 [get_ports {ddr4_rtl_0_adr[9]}]
set_property PACKAGE_PIN C27 [get_ports {ddr4_rtl_0_adr[10]}]
set_property PACKAGE_PIN B28 [get_ports {ddr4_rtl_0_adr[11]}]
set_property PACKAGE_PIN F30 [get_ports {ddr4_rtl_0_adr[12]}]
set_property PACKAGE_PIN F31 [get_ports {ddr4_rtl_0_adr[13]}]
set_property PACKAGE_PIN E29 [get_ports {ddr4_rtl_0_adr[14]}]
set_property PACKAGE_PIN D29 [get_ports {ddr4_rtl_0_adr[15]}]
set_property PACKAGE_PIN E30 [get_ports {ddr4_rtl_0_adr[16]}]
set_property PACKAGE_PIN G30 [get_ports {ddr4_rtl_0_dq[0]}]
set_property PACKAGE_PIN F26 [get_ports {ddr4_rtl_0_dq[1]}]
set_property PACKAGE_PIN H28 [get_ports {ddr4_rtl_0_dq[2]}]
set_property PACKAGE_PIN G26 [get_ports {ddr4_rtl_0_dq[3]}]
set_property PACKAGE_PIN H29 [get_ports {ddr4_rtl_0_dq[4]}]
set_property PACKAGE_PIN J27 [get_ports {ddr4_rtl_0_dq[5]}]
set_property PACKAGE_PIN G31 [get_ports {ddr4_rtl_0_dq[6]}]
set_property PACKAGE_PIN J26 [get_ports {ddr4_rtl_0_dq[7]}]
set_property PACKAGE_PIN M25 [get_ports {ddr4_rtl_0_dq[8]}]
set_property PACKAGE_PIN L27 [get_ports {ddr4_rtl_0_dq[9]}]
set_property PACKAGE_PIN J25 [get_ports {ddr4_rtl_0_dq[10]}]
set_property PACKAGE_PIN K28 [get_ports {ddr4_rtl_0_dq[11]}]
set_property PACKAGE_PIN L25 [get_ports {ddr4_rtl_0_dq[12]}]
set_property PACKAGE_PIN J29 [get_ports {ddr4_rtl_0_dq[13]}]
set_property PACKAGE_PIN K25 [get_ports {ddr4_rtl_0_dq[14]}]
set_property PACKAGE_PIN L28 [get_ports {ddr4_rtl_0_dq[15]}]
set_property PACKAGE_PIN M18 [get_ports {ddr4_rtl_0_dq[16]}]
set_property PACKAGE_PIN L15 [get_ports {ddr4_rtl_0_dq[17]}]
set_property PACKAGE_PIN L18 [get_ports {ddr4_rtl_0_dq[18]}]
set_property PACKAGE_PIN M16 [get_ports {ddr4_rtl_0_dq[19]}]
set_property PACKAGE_PIN N19 [get_ports {ddr4_rtl_0_dq[20]}]
set_property PACKAGE_PIN M15 [get_ports {ddr4_rtl_0_dq[21]}]
set_property PACKAGE_PIN N18 [get_ports {ddr4_rtl_0_dq[22]}]
set_property PACKAGE_PIN N16 [get_ports {ddr4_rtl_0_dq[23]}]
set_property PACKAGE_PIN K17 [get_ports {ddr4_rtl_0_dq[24]}]
set_property PACKAGE_PIN G16 [get_ports {ddr4_rtl_0_dq[25]}]
set_property PACKAGE_PIN H18 [get_ports {ddr4_rtl_0_dq[26]}]
set_property PACKAGE_PIN H17 [get_ports {ddr4_rtl_0_dq[27]}]
set_property PACKAGE_PIN J17 [get_ports {ddr4_rtl_0_dq[28]}]
set_property PACKAGE_PIN H16 [get_ports {ddr4_rtl_0_dq[29]}]
set_property PACKAGE_PIN H19 [get_ports {ddr4_rtl_0_dq[30]}]
set_property PACKAGE_PIN J16 [get_ports {ddr4_rtl_0_dq[31]}]
set_property PACKAGE_PIN H26 [get_ports {ddr4_rtl_0_dqs_t[0]}]
set_property PACKAGE_PIN M26 [get_ports {ddr4_rtl_0_dqs_t[1]}]
set_property PACKAGE_PIN L17 [get_ports {ddr4_rtl_0_dqs_t[2]}]
set_property PACKAGE_PIN K19 [get_ports {ddr4_rtl_0_dqs_t[3]}]
set_property PACKAGE_PIN D30 [get_ports {ddr4_rtl_0_ba[0]}]
set_property PACKAGE_PIN D26 [get_ports {ddr4_rtl_0_ba[1]}]
set_property PACKAGE_PIN D27 [get_ports {ddr4_rtl_0_bg[0]}]
set_property PACKAGE_PIN E27 [get_ports {ddr4_rtl_0_ck_t[0]}]
set_property PACKAGE_PIN D31 [get_ports {ddr4_rtl_0_odt[0]}]
set_property PACKAGE_PIN G28 [get_ports {ddr4_rtl_0_dm_n[0]}]
set_property PACKAGE_PIN K29 [get_ports {ddr4_rtl_0_dm_n[1]}]
set_property PACKAGE_PIN N14 [get_ports {ddr4_rtl_0_dm_n[2]}]
set_property PACKAGE_PIN K15 [get_ports {ddr4_rtl_0_dm_n[3]}]
set_property PACKAGE_PIN G29 [get_ports {ddr4_rtl_0_cs_n[0]}]
set_property PACKAGE_PIN J30 [get_ports ddr4_rtl_0_act_n]
set_property PACKAGE_PIN K30 [get_ports {ddr4_rtl_0_cke[0]}]
set_property PACKAGE_PIN M14 [get_ports ddr4_rtl_0_reset_n]

set_property IOSTANDARD LVDS [get_ports ddr4_ref_0_clk_n]
set_property -dict {PACKAGE_PIN F27 IOSTANDARD LVDS} [get_ports ddr4_ref_0_clk_p]
set_property -dict {PACKAGE_PIN K27 IOSTANDARD LVCMOS12} [get_ports ddr4_rtl_0_par]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS12} [get_ports ddr4_rtl_0_alert_n]

set_property PACKAGE_PIN V9 [get_ports ref_clk_c_n]
set_property PACKAGE_PIN V10 [get_ports ref_clk_c_p]

set_property PACKAGE_PIN Y2 [get_ports {rx_data_c_p[0]}]
set_property PACKAGE_PIN Y1 [get_ports {rx_data_c_n[0]}]
set_property PACKAGE_PIN Y6 [get_ports {tx_data_c_p[0]}]
set_property PACKAGE_PIN Y5 [get_ports {tx_data_c_n[0]}]
set_property PACKAGE_PIN W4 [get_ports {rx_data_c_p[1]}]
set_property PACKAGE_PIN W3 [get_ports {rx_data_c_n[1]}]
set_property PACKAGE_PIN W8 [get_ports {tx_data_c_p[1]}]
set_property PACKAGE_PIN W7 [get_ports {tx_data_c_n[1]}]
set_property PACKAGE_PIN V2 [get_ports {rx_data_c_p[2]}]
set_property PACKAGE_PIN V1 [get_ports {rx_data_c_n[2]}]
set_property PACKAGE_PIN V6 [get_ports {tx_data_c_p[2]}]
set_property PACKAGE_PIN V5 [get_ports {tx_data_c_n[2]}]
set_property PACKAGE_PIN U4 [get_ports {rx_data_c_p[3]}]
set_property PACKAGE_PIN U3 [get_ports {rx_data_c_n[3]}]
set_property PACKAGE_PIN U8 [get_ports {tx_data_c_p[3]}]
set_property PACKAGE_PIN U7 [get_ports {tx_data_c_n[3]}]

set_property PACKAGE_PIN W11 [get_ports ref_clk_d_n]
set_property PACKAGE_PIN W12 [get_ports ref_clk_d_p]

set_property PACKAGE_PIN T2 [get_ports {rx_data_d_p[0]}]
set_property PACKAGE_PIN T1 [get_ports {rx_data_d_n[0]}]
set_property PACKAGE_PIN T6 [get_ports {tx_data_d_p[0]}]
set_property PACKAGE_PIN T5 [get_ports {tx_data_d_n[0]}]
set_property PACKAGE_PIN R4 [get_ports {rx_data_d_p[1]}]
set_property PACKAGE_PIN R3 [get_ports {rx_data_d_n[1]}]
set_property PACKAGE_PIN R8 [get_ports {tx_data_d_p[1]}]
set_property PACKAGE_PIN R7 [get_ports {tx_data_d_n[1]}]
set_property PACKAGE_PIN P2 [get_ports {rx_data_d_p[2]}]
set_property PACKAGE_PIN P1 [get_ports {rx_data_d_n[2]}]
set_property PACKAGE_PIN P6 [get_ports {tx_data_d_p[2]}]
set_property PACKAGE_PIN P5 [get_ports {tx_data_d_n[2]}]
set_property PACKAGE_PIN N4 [get_ports {rx_data_d_p[3]}]
set_property PACKAGE_PIN N3 [get_ports {rx_data_d_n[3]}]
set_property PACKAGE_PIN N8 [get_ports {tx_data_d_p[3]}]
set_property PACKAGE_PIN N7 [get_ports {tx_data_d_n[3]}]

set_property IOSTANDARD LVDS [get_ports core_clk_c_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports core_clk_c_p]
set_property PACKAGE_PIN AP25 [get_ports core_clk_c_p]
set_property PACKAGE_PIN AP26 [get_ports core_clk_c_n]
set_property IOSTANDARD LVDS [get_ports core_clk_c_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports core_clk_c_n]
set_property IOSTANDARD LVDS [get_ports core_clk_d_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports core_clk_d_p]
set_property PACKAGE_PIN AP24 [get_ports core_clk_d_p]
set_property PACKAGE_PIN AR24 [get_ports core_clk_d_n]
set_property IOSTANDARD LVDS [get_ports core_clk_d_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports core_clk_d_n]

set_property -dict {PACKAGE_PIN H36 IOSTANDARD LVDS} [get_ports rx_sync_c_p]
set_property -dict {PACKAGE_PIN H37 IOSTANDARD LVDS} [get_ports rx_sync_c_n]
set_property -dict {PACKAGE_PIN AH24 IOSTANDARD LVDS} [get_ports rx_os_sync_c_p]
set_property -dict {PACKAGE_PIN AJ24 IOSTANDARD LVDS} [get_ports rx_os_sync_c_n]
set_property IOSTANDARD LVDS [get_ports tx_sync_c_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_c_p]
set_property PACKAGE_PIN C38 [get_ports tx_sync_c_p]
set_property PACKAGE_PIN C39 [get_ports tx_sync_c_n]
set_property IOSTANDARD LVDS [get_ports tx_sync_c_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_c_n]
set_property PACKAGE_PIN J32 [get_ports tx_sync_c_1_p]
set_property IOSTANDARD LVDS [get_ports tx_sync_c_1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_c_1_p]
set_property PACKAGE_PIN H33 [get_ports tx_sync_c_1_n]
set_property IOSTANDARD LVDS [get_ports tx_sync_c_1_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_c_1_n]
set_property IOSTANDARD LVDS [get_ports sysref_c_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports sysref_c_p]
set_property PACKAGE_PIN AN23 [get_ports sysref_c_p]
set_property PACKAGE_PIN AN24 [get_ports sysref_c_n]
set_property IOSTANDARD LVDS [get_ports sysref_c_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports sysref_c_n]

set_property -dict {PACKAGE_PIN AG22 IOSTANDARD LVCMOS18} [get_ports adrv9009_tx1_enable_c]
set_property -dict {PACKAGE_PIN AG23 IOSTANDARD LVCMOS18} [get_ports adrv9009_tx2_enable_c]
set_property -dict {PACKAGE_PIN AH22 IOSTANDARD LVCMOS18} [get_ports adrv9009_rx1_enable_c]
set_property -dict {PACKAGE_PIN AJ22 IOSTANDARD LVCMOS18} [get_ports adrv9009_rx2_enable_c]
set_property -dict {PACKAGE_PIN H31 IOSTANDARD LVCMOS18} [get_ports adrv9009_reset_b_c]
set_property -dict {PACKAGE_PIN C37 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpint_c]
set_property -dict {PACKAGE_PIN E32 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_00_c]
set_property -dict {PACKAGE_PIN A32 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_01_c]
set_property -dict {PACKAGE_PIN D32 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_02_c]
set_property -dict {PACKAGE_PIN AW26 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_03_c]
set_property -dict {PACKAGE_PIN AR25 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_04_c]
set_property -dict {PACKAGE_PIN AR22 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_05_c]
set_property -dict {PACKAGE_PIN E35 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_06_c]
set_property -dict {PACKAGE_PIN AK22 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_07_c]
set_property -dict {PACKAGE_PIN G33 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_08_c]

set_property -dict {PACKAGE_PIN F37 IOSTANDARD LVDS} [get_ports rx_sync_d_p]
set_property -dict {PACKAGE_PIN E37 IOSTANDARD LVDS} [get_ports rx_sync_d_n]
set_property -dict {PACKAGE_PIN AM23 IOSTANDARD LVDS} [get_ports rx_os_sync_d_p]
set_property -dict {PACKAGE_PIN AM24 IOSTANDARD LVDS} [get_ports rx_os_sync_d_n]
set_property IOSTANDARD LVDS [get_ports tx_sync_d_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_d_p]
set_property PACKAGE_PIN B33 [get_ports tx_sync_d_p]
set_property PACKAGE_PIN B34 [get_ports tx_sync_d_n]
set_property IOSTANDARD LVDS [get_ports tx_sync_d_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_d_n]
set_property PACKAGE_PIN H38 [get_ports tx_sync_d_1_p]
set_property IOSTANDARD LVDS [get_ports tx_sync_d_1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_d_1_p]
set_property PACKAGE_PIN H39 [get_ports tx_sync_d_1_n]
set_property IOSTANDARD LVDS [get_ports tx_sync_d_1_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_d_1_n]
set_property IOSTANDARD LVDS [get_ports sysref_d_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports sysref_d_p]
set_property PACKAGE_PIN AN22 [get_ports sysref_d_p]
set_property PACKAGE_PIN AP22 [get_ports sysref_d_n]
set_property IOSTANDARD LVDS [get_ports sysref_d_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports sysref_d_n]

set_property -dict {PACKAGE_PIN E39 IOSTANDARD LVCMOS18} [get_ports adrv9009_tx1_enable_d]
set_property -dict {PACKAGE_PIN D39 IOSTANDARD LVCMOS18} [get_ports adrv9009_tx2_enable_d]
set_property -dict {PACKAGE_PIN G38 IOSTANDARD LVCMOS18} [get_ports adrv9009_rx1_enable_d]
set_property -dict {PACKAGE_PIN G39 IOSTANDARD LVCMOS18} [get_ports adrv9009_rx2_enable_d]
set_property -dict {PACKAGE_PIN H32 IOSTANDARD LVCMOS18} [get_ports adrv9009_reset_b_d]
set_property -dict {PACKAGE_PIN B38 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpint_d]
set_property -dict {PACKAGE_PIN E33 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_00_d]
set_property -dict {PACKAGE_PIN A33 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_01_d]
set_property -dict {PACKAGE_PIN C32 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_02_d]
set_property -dict {PACKAGE_PIN AW27 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_03_d]
set_property -dict {PACKAGE_PIN AT25 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_04_d]
set_property -dict {PACKAGE_PIN AT22 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_05_d]
set_property -dict {PACKAGE_PIN D35 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_06_d]
set_property -dict {PACKAGE_PIN AK23 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_07_d]
set_property -dict {PACKAGE_PIN G34 IOSTANDARD LVCMOS18} [get_ports adrv9009_gpio_08_d]

set_property -dict {PACKAGE_PIN AK24 IOSTANDARD LVCMOS18} [get_ports hmc7044_fmc_reset]
set_property -dict {PACKAGE_PIN AK25 IOSTANDARD LVCMOS18} [get_ports hmc7044_fmc_sync]
set_property -dict {PACKAGE_PIN AL25 IOSTANDARD LVCMOS18} [get_ports hmc7044_fmc_gpio_1]
set_property -dict {PACKAGE_PIN AM25 IOSTANDARD LVCMOS18} [get_ports hmc7044_fmc_gpio_2]
set_property -dict {PACKAGE_PIN AW24 IOSTANDARD LVCMOS18} [get_ports hmc7044_fmc_gpio_3]
set_property -dict {PACKAGE_PIN AW25 IOSTANDARD LVCMOS18} [get_ports hmc7044_fmc_gpio_4]

set_property -dict {PACKAGE_PIN F38 IOSTANDARD LVCMOS18} [get_ports spi_fmc_clk]
set_property -dict {PACKAGE_PIN A38 IOSTANDARD LVCMOS18} [get_ports spi_fmc_sdio]
set_property -dict {PACKAGE_PIN A37 IOSTANDARD LVCMOS18} [get_ports spi_fmc_miso]

set_property -dict {PACKAGE_PIN AJ25 IOSTANDARD LVCMOS18} [get_ports spi_csn_adrv9009_c]
set_property -dict {PACKAGE_PIN AL22 IOSTANDARD LVCMOS18} [get_ports spi_csn_adrv9009_d]
set_property -dict {PACKAGE_PIN E38 IOSTANDARD LVCMOS18} [get_ports spi_csn_fmc_hmc7044]

create_clock -period 4.000 -name tx_fmc_dev_clk [get_ports core_clk_c_p]
create_clock -period 4.000 -name rx_fmc_dev_clk [get_ports core_clk_d_p]
create_clock -period 4.000 -name jesd_tx_fmc_ref_clk [get_ports ref_clk_c_p]
create_clock -period 4.000 -name jesd_rx_fmc_ref_clk [get_ports ref_clk_d_p]

set_input_delay -clock rx_fmc_dev_clk -max 4.000 [get_ports sysref_c_p]
set_input_delay -clock rx_fmc_dev_clk -min 4.000 [get_ports sysref_c_p]

set_input_delay -clock tx_fmc_dev_clk -max 4.000 [get_ports sysref_d_p]
set_input_delay -clock tx_fmc_dev_clk -min 4.000 [get_ports sysref_d_p]

create_clock -period 40.000 -name spi1_clk [get_pins -hier */EMIOSPI1SCLKO]

