apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-project-ad469x_evb-de10nano
  title: AD469X-EVB HDL project
  description: >
    The AD469X HDL reference design provides all the interfaces that are necessary
    to interact with the devices on the EVAL-AD4696 and EVAL-AD4692-ARDZ boards.

    The design has a SPI Engine instance to control and acquire data from the AD4696/AD4692
    16-bit precision ADCs, providing support to capture continuous samples at maximum
    sampling rate. The PWM_OFFLOAD parameter allows selecting the appropriate offload
    trigger and CNV gating scheme for each device.

    It targets the Intel Altera DE10NANO.
  version: main
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/analogdevicesinc/hdl/tree/main/projects/ad469x_evb/de10nano
  tags:
  - ad4692
  - ad4696
  - de10nano
  - eval-ad4692-ardz
  - eval-ad4696
  - hdl
  - project
  - reference-design
  links:
  - url: https://analogdevicesinc.github.io/hdl/projects/ad469x_evb/index.html
    title: Documentation
    icon: web
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
