###############################################################################
## Copyright (C) 2014-2023 Analog Devices, Inc. All rights reserved.
### SPDX short identifier: ADIBSD
###############################################################################

# Implementation-only constraints — clk_fpga_0 is generated by the PS7 IP and
# is not visible during OOC synthesis, so this must not run at synthesis.

# qspi_clk (external, from Alif) is async to both PS-generated clocks:
# clk_fpga_0 (100 MHz, sys_cpu_clk / AXI) and clk_fpga_1 (200 MHz, now the
# QSPI slave sys_clk). Grouping keeps Vivado from timing cross-domain paths
# — the CDC synchronizers and cs_n debouncer handle metastability.
# -include_generated_clocks on qspi_clk also pulls in the MMCM-generated
# clock on the compensated sclk output.
set_clock_groups -asynchronous \
  -group [get_clocks -include_generated_clocks qspi_clk] \
  -group [get_clocks -include_generated_clocks clk_fpga_0] \
  -group [get_clocks -include_generated_clocks clk_fpga_1]


