
set_property CONFIG.PCW_PRESET_BANK0_VOLTAGE                      {LVCMOS 1.8V}           [get_bd_cells sys_ps7]
set_property CONFIG.PCW_PRESET_BANK1_VOLTAGE                      {LVCMOS 1.8V}           [get_bd_cells sys_ps7]

set_property CONFIG.PCW_GPIO_MIO_GPIO_ENABLE                      {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_ENET0_PERIPHERAL_ENABLE                   {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_ENET0_ENET0_IO                            {MIO 16 .. 27}          [get_bd_cells sys_ps7]
set_property CONFIG.PCW_ENET0_GRP_MDIO_ENABLE                     {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_ENET0_GRP_MDIO_IO                         {MIO 52 .. 53}          [get_bd_cells sys_ps7]
set_property CONFIG.PCW_ENET0_RESET_ENABLE                        {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_ENET0_RESET_IO                            {MIO 47}                [get_bd_cells sys_ps7]

set_property CONFIG.PCW_USB0_PERIPHERAL_ENABLE                    {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_USB0_RESET_ENABLE                         {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_USB0_RESET_IO                             {MIO 7}                 [get_bd_cells sys_ps7]
set_property CONFIG.PCW_I2C0_PERIPHERAL_ENABLE                    {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_I2C0_I2C0_IO                              {MIO 50 .. 51}          [get_bd_cells sys_ps7]
set_property CONFIG.PCW_I2C0_RESET_ENABLE                         {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_I2C0_RESET_IO                             {MIO 46}                [get_bd_cells sys_ps7]

set_property CONFIG.PCW_SD0_PERIPHERAL_ENABLE                     {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_SD0_GRP_CD_ENABLE                         {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_SD0_GRP_CD_IO                             {MIO 14}                [get_bd_cells sys_ps7]
set_property CONFIG.PCW_SD0_GRP_WP_ENABLE                         {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_SDIO_PERIPHERAL_FREQMHZ                   {50}                    [get_bd_cells sys_ps7]

set_property CONFIG.PCW_UART1_PERIPHERAL_ENABLE                   {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UART_PERIPHERAL_FREQMHZ                   {50}                    [get_bd_cells sys_ps7]

set_property CONFIG.PCW_QSPI_PERIPHERAL_ENABLE                    {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_QSPI_GRP_SINGLE_SS_ENABLE                 {0}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_QSPI_GRP_IO1_ENABLE                       {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_QSPI_GRP_FBCLK_ENABLE                     {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_TTC0_PERIPHERAL_ENABLE                    {1}                     [get_bd_cells sys_ps7]

set_property CONFIG.PCW_UIPARAM_DDR_PARTNO                        {Custom}                [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_BUS_WIDTH                     {32 Bit}                [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_USE_INTERNAL_VREF             {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_DRAM_WIDTH                    {16 Bits}               [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_DEVICE_CAPACITY               {4096 MBits}            [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_SPEED_BIN                     {DDR3_1066F}            [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_COL_ADDR_COUNT                {10}                    [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_CL                            {7}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_CWL                           {5}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_T_RCD                         {7}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_T_RP                          {7}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_T_RC                          {49.5}                  [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_T_RAS_MIN                     {36.0}                  [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_T_FAW                         {45.0}                  [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_TRAIN_WRITE_LEVEL             {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_TRAIN_READ_GATE               {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_TRAIN_DATA_EYE                {1}                     [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0            {0.078}                 [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1            {0.074}                 [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2            {-0.059}                [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3            {-0.055}                [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY0                  {0.482}                 [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY1                  {0.484}                 [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY2                  {0.417}                 [get_bd_cells sys_ps7]
set_property CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY3                  {0.416}                 [get_bd_cells sys_ps7]

set_property CONFIG.PCW_MIO_16_IOTYPE                             {HSTL 1.8V}             [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_16_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_17_IOTYPE                             {HSTL 1.8V}             [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_17_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_18_IOTYPE                             {HSTL 1.8V}             [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_18_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_19_IOTYPE                             {HSTL 1.8V}             [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_19_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_20_IOTYPE                             {HSTL 1.8V}             [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_20_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_21_IOTYPE                             {HSTL 1.8V}             [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_21_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_22_IOTYPE                             {HSTL 1.8V}             [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_22_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_23_IOTYPE                             {HSTL 1.8V}             [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_23_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_24_IOTYPE                             {HSTL 1.8V}             [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_24_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_25_IOTYPE                             {HSTL 1.8V}             [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_25_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_26_IOTYPE                             {HSTL 1.8V}             [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_26_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_27_IOTYPE                             {HSTL 1.8V}             [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_27_PULLUP                             {disabled}              [get_bd_cells sys_ps7]

set_property CONFIG.PCW_MIO_28_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_29_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_30_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_31_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_32_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_33_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_34_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_35_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_36_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_37_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_38_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_39_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_40_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_41_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_42_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_43_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_44_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_45_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_48_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_49_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_52_PULLUP                             {disabled}              [get_bd_cells sys_ps7]
set_property CONFIG.PCW_MIO_53_PULLUP                             {disabled}              [get_bd_cells sys_ps7]


