set_property PACKAGE_PIN P16 [get_ports gpio_en_agc]
set_property PACKAGE_PIN N17 [get_ports gpio_resetb]
set_property PACKAGE_PIN T10 [get_ports {gpio_ctl[0]}]
set_property PACKAGE_PIN Y12 [get_ports {gpio_ctl[1]}]
set_property PACKAGE_PIN Y13 [get_ports {gpio_ctl[2]}]
set_property PACKAGE_PIN V11 [get_ports {gpio_ctl[3]}]
set_property PACKAGE_PIN T11 [get_ports {gpio_status[0]}]
set_property PACKAGE_PIN T14 [get_ports {gpio_status[1]}]
set_property PACKAGE_PIN T15 [get_ports {gpio_status[2]}]
set_property PACKAGE_PIN T17 [get_ports {gpio_status[3]}]
set_property PACKAGE_PIN T19 [get_ports {gpio_status[4]}]
set_property PACKAGE_PIN T20 [get_ports {gpio_status[5]}]
set_property PACKAGE_PIN U13 [get_ports {gpio_status[6]}]
set_property PACKAGE_PIN V13 [get_ports {gpio_status[7]}]
set_property PACKAGE_PIN N20 [get_ports rx_clk_in]
set_property PACKAGE_PIN U18 [get_ports rx_frame_in]
set_property PACKAGE_PIN Y19 [get_ports {rx_data_in[0]}]
set_property PACKAGE_PIN Y18 [get_ports {rx_data_in[1]}]
set_property PACKAGE_PIN V18 [get_ports {rx_data_in[2]}]
set_property PACKAGE_PIN V17 [get_ports {rx_data_in[3]}]
set_property PACKAGE_PIN W20 [get_ports {rx_data_in[4]}]
set_property PACKAGE_PIN V20 [get_ports {rx_data_in[5]}]
set_property PACKAGE_PIN R17 [get_ports {rx_data_in[6]}]
set_property PACKAGE_PIN R16 [get_ports {rx_data_in[7]}]
set_property PACKAGE_PIN W19 [get_ports {rx_data_in[8]}]
set_property PACKAGE_PIN W18 [get_ports {rx_data_in[9]}]
set_property PACKAGE_PIN W16 [get_ports {rx_data_in[10]}]
set_property PACKAGE_PIN V16 [get_ports {rx_data_in[11]}]
set_property PACKAGE_PIN Y14 [get_ports {tx_data_out[0]}]
set_property PACKAGE_PIN W14 [get_ports {tx_data_out[1]}]
set_property PACKAGE_PIN U12 [get_ports {tx_data_out[2]}]
set_property PACKAGE_PIN T12 [get_ports {tx_data_out[3]}]
set_property PACKAGE_PIN U15 [get_ports {tx_data_out[4]}]
set_property PACKAGE_PIN U14 [get_ports {tx_data_out[5]}]
set_property PACKAGE_PIN U17 [get_ports {tx_data_out[6]}]
set_property PACKAGE_PIN T16 [get_ports {tx_data_out[7]}]
set_property PACKAGE_PIN W13 [get_ports {tx_data_out[8]}]
set_property PACKAGE_PIN V12 [get_ports {tx_data_out[9]}]
set_property PACKAGE_PIN W15 [get_ports {tx_data_out[10]}]
set_property PACKAGE_PIN V15 [get_ports {tx_data_out[11]}]
set_property PACKAGE_PIN N18 [get_ports tx_clk_out]
set_property PACKAGE_PIN Y16 [get_ports tx_frame_out]
set_property PACKAGE_PIN P14 [get_ports txnrx]
set_property PACKAGE_PIN M15 [get_ports clk_out]
set_property PACKAGE_PIN R18 [get_ports enable]
set_property PACKAGE_PIN P18 [get_ports spi_csn]
set_property PACKAGE_PIN R14 [get_ports spi_clk]
set_property PACKAGE_PIN P15 [get_ports spi_mosi]
set_property PACKAGE_PIN R19 [get_ports spi_miso]
set_property PACKAGE_PIN G15 [get_ports pl_spi_clk_o]
set_property PACKAGE_PIN H18 [get_ports pl_spi_miso]
set_property PACKAGE_PIN G17 [get_ports pl_spi_mosi]
set_property PACKAGE_PIN J18 [get_ports iic_scl]
set_property PACKAGE_PIN H17 [get_ports iic_sda]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_en_agc]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_resetb]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_ctl[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_ctl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_ctl[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_ctl[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_status[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_status[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_status[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_status[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_status[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_status[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_status[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_status[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports iic_scl]
set_property IOSTANDARD LVCMOS33 [get_ports iic_sda]
set_property IOSTANDARD LVCMOS33 [get_ports pl_spi_clk_o]
set_property IOSTANDARD LVCMOS33 [get_ports pl_spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports pl_spi_mosi]
set_property IOSTANDARD LVCMOS18 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS18 [get_ports spi_csn]
set_property IOSTANDARD LVCMOS18 [get_ports spi_miso]
set_property IOSTANDARD LVCMOS18 [get_ports spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out]
set_property IOSTANDARD LVCMOS18 [get_ports {rx_data_in[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rx_data_in[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rx_data_in[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rx_data_in[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rx_data_in[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rx_data_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rx_data_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rx_data_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rx_data_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rx_data_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rx_data_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rx_data_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tx_data_out[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tx_data_out[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tx_data_out[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tx_data_out[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tx_data_out[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tx_data_out[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tx_data_out[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tx_data_out[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tx_data_out[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tx_data_out[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tx_data_out[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tx_data_out[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports enable]
set_property IOSTANDARD LVCMOS18 [get_ports rx_clk_in]
set_property IOSTANDARD LVCMOS18 [get_ports rx_frame_in]
set_property IOSTANDARD LVCMOS18 [get_ports tx_clk_out]
set_property IOSTANDARD LVCMOS18 [get_ports tx_frame_out]
set_property IOSTANDARD LVCMOS18 [get_ports txnrx]


# set_property PACKAGE_PIN J16 [get_ports ltc2630_sclk_0]
# set_property IOSTANDARD LVCMOS33 [get_ports ltc2630_sclk_0]

# set_property PACKAGE_PIN K16 [get_ports ltc2630_ncs_0]
# set_property IOSTANDARD LVCMOS33 [get_ports ltc2630_ncs_0]

# set_property PACKAGE_PIN J15 [get_ports ltc2630_mosi_0]
# set_property IOSTANDARD LVCMOS33 [get_ports ltc2630_mosi_0]

create_clock -name rx_clk -period  16.27 [get_ports rx_clk_in]
create_clock -name clk_fpga_0 -period 10 [get_pins "i_system_wrapper/system_i/sys_ps7/inst/PS7_i/FCLKCLK[0]"]
create_clock -name clk_fpga_1 -period  5 [get_pins "i_system_wrapper/system_i/sys_ps7/inst/PS7_i/FCLKCLK[1]"]

create_clock -name spi0_clk      -period 40   [get_pins -hier */EMIOSPI0SCLKO]

set_input_jitter clk_fpga_0 0.3
set_input_jitter clk_fpga_1 0.15

set_property IOSTANDARD LVCMOS33 [get_ports VCRX1_H]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX1_L]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX2_H]
set_property IOSTANDARD LVCMOS33 [get_ports VCRX2_L]
set_property IOSTANDARD LVCMOS33 [get_ports VCTX1_H]
set_property IOSTANDARD LVCMOS33 [get_ports VCTX1_L]
set_property IOSTANDARD LVCMOS33 [get_ports VCTX2_H]
set_property IOSTANDARD LVCMOS33 [get_ports VCTX2_L]
set_property PACKAGE_PIN G14 [get_ports VCRX1_H]
set_property PACKAGE_PIN C20 [get_ports VCRX1_L]
set_property PACKAGE_PIN B19 [get_ports VCTX1_H]
set_property PACKAGE_PIN B20 [get_ports VCTX1_L]
set_property PACKAGE_PIN E17 [get_ports VCRX2_H]
set_property PACKAGE_PIN A20 [get_ports VCRX2_L]
set_property PACKAGE_PIN D18 [get_ports VCTX2_H]
set_property PACKAGE_PIN D19 [get_ports VCTX2_L]

set_false_path -from [get_cells -hier *wr_ptr_grey_reg*] -to [get_cells -hier *wr_ptr_f_reg*]