
set dac_fifo_name axi_ad9371_dacfifo
set dac_fifo_address_width 10
set dac_data_width 128
set dac_dma_data_width 128

source $ad_hdl_dir/projects/common/zcu102/zcu102_system_bd.tcl
source $ad_hdl_dir/projects/common/xilinx/dacfifo_bd.tcl
source ../common/adrv9371x_bd.tcl

ad_ip_parameter sys_ps8 CONFIG.PSU__FPGA_PL2_ENABLE 1
ad_ip_parameter sys_ps8 CONFIG.PSU__CRL_APB__PL2_REF_CTRL__SRCSEL {IOPLL}
ad_ip_parameter sys_ps8 CONFIG.PSU__CRL_APB__PL2_REF_CTRL__FREQMHZ 150
ad_connect sys_dma_clk sys_ps8/pl_clk2
ad_ip_instance proc_sys_reset sys_dma_rstgen
ad_ip_parameter sys_dma_rstgen CONFIG.C_EXT_RST_WIDTH 1
ad_connect sys_rstgen/peripheral_reset sys_dma_rstgen/ext_reset_in
ad_connect sys_dma_clk sys_dma_rstgen/slowest_sync_clk
ad_connect sys_dma_resetn sys_dma_rstgen/peripheral_aresetn
ad_connect sys_dma_reset sys_dma_rstgen/peripheral_reset

ad_ip_instance util_ds_buf axi_ad9371_tx_bufg
ad_ip_parameter axi_ad9371_tx_bufg CONFIG.C_BUF_TYPE {BUFG_GT}
ad_connect axi_adrv9371x_xcvr_0/txoutclk axi_ad9371_tx_bufg/BUFG_GT_I
ad_connect axi_ad9371_tx_bufg/BUFG_GT_O axi_ad9371_tx_clkgen/clk
ad_connect axi_ad9371_tx_bufg/BUFG_GT_CE VCC
ad_connect axi_ad9371_tx_bufg/BUFG_GT_CLR GND
ad_connect axi_ad9371_tx_bufg/BUFG_GT_DIV GND
ad_connect axi_ad9371_tx_bufg/BUFG_GT_CEMASK GND
ad_connect axi_ad9371_tx_bufg/BUFG_GT_CLRMASK GND

ad_ip_instance util_ds_buf axi_ad9371_rx_bufg
ad_ip_parameter axi_ad9371_rx_bufg CONFIG.C_BUF_TYPE {BUFG_GT}
ad_connect axi_adrv9371x_xcvr_0/rxoutclk axi_ad9371_rx_bufg/BUFG_GT_I
ad_connect axi_ad9371_rx_bufg/BUFG_GT_O axi_ad9371_rx_clkgen/clk
ad_connect axi_ad9371_rx_bufg/BUFG_GT_CE VCC
ad_connect axi_ad9371_rx_bufg/BUFG_GT_CLR GND
ad_connect axi_ad9371_rx_bufg/BUFG_GT_DIV GND
ad_connect axi_ad9371_rx_bufg/BUFG_GT_CEMASK GND
ad_connect axi_ad9371_rx_bufg/BUFG_GT_CLRMASK GND

ad_ip_instance util_ds_buf axi_ad9371_rx_os_bufg
ad_ip_parameter axi_ad9371_rx_os_bufg CONFIG.C_BUF_TYPE {BUFG_GT}
ad_connect axi_adrv9371x_xcvr_1/rxoutclk axi_ad9371_rx_os_bufg/BUFG_GT_I
ad_connect axi_ad9371_rx_os_bufg/BUFG_GT_O axi_ad9371_rx_os_clkgen/clk
ad_connect axi_ad9371_rx_os_bufg/BUFG_GT_CE VCC
ad_connect axi_ad9371_rx_os_bufg/BUFG_GT_CLR GND
ad_connect axi_ad9371_rx_os_bufg/BUFG_GT_DIV GND
ad_connect axi_ad9371_rx_os_bufg/BUFG_GT_CEMASK GND
ad_connect axi_ad9371_rx_os_bufg/BUFG_GT_CLRMASK GND

ad_ip_parameter axi_adrv9371x_xcvr_0 CONFIG.GT_Location {X1Y8}
ad_ip_parameter axi_adrv9371x_xcvr_1 CONFIG.GT_Location {X1Y10}

ad_connect axi_adrv9371x_xcvr_0/gt0_rx axi_ad9371_rx_os_jesd/rx_phy1
ad_connect axi_adrv9371x_xcvr_0/gt1_rx axi_ad9371_rx_jesd/rx_phy0
ad_connect axi_adrv9371x_xcvr_1/gt0_rx axi_ad9371_rx_os_jesd/rx_phy0
ad_connect axi_adrv9371x_xcvr_1/gt1_rx axi_ad9371_rx_jesd/rx_phy1

ad_connect axi_ad9371_tx_jesd/tx_phy2 axi_adrv9371x_xcvr_0/gt0_tx
ad_connect axi_ad9371_tx_jesd/tx_phy3 axi_adrv9371x_xcvr_0/gt1_tx
ad_connect axi_ad9371_tx_jesd/tx_phy1 axi_adrv9371x_xcvr_1/gt0_tx
ad_connect axi_ad9371_tx_jesd/tx_phy0 axi_adrv9371x_xcvr_1/gt1_tx

