###############################################################################
## Copyright (C) 2020-2023 Analog Devices, Inc. All rights reserved.
### SPDX short identifier: ADIBSD
###############################################################################

#
## mxfe
#

set_property -dict {PACKAGE_PIN R34 IOSTANDARD LVCMOS18} [get_ports {agc0[0]}]
set_property -dict {PACKAGE_PIN P34 IOSTANDARD LVCMOS18} [get_ports {agc0[1]}]
set_property -dict {PACKAGE_PIN R31 IOSTANDARD LVCMOS18} [get_ports {agc1[0]}]
set_property -dict {PACKAGE_PIN P31 IOSTANDARD LVCMOS18} [get_ports {agc1[1]}]
set_property -dict {PACKAGE_PIN N32 IOSTANDARD LVCMOS18} [get_ports {agc2[0]}]
set_property -dict {PACKAGE_PIN M32 IOSTANDARD LVCMOS18} [get_ports {agc2[1]}]
set_property -dict {PACKAGE_PIN M35 IOSTANDARD LVCMOS18} [get_ports {agc3[0]}]
set_property -dict {PACKAGE_PIN L35 IOSTANDARD LVCMOS18} [get_ports {agc3[1]}]
set_property IOSTANDARD LVDS [get_ports clkin6_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports clkin6_n]
set_property DQS_BIAS TRUE [get_ports clkin6_n]
set_property PACKAGE_PIN P35 [get_ports clkin6_p]
set_property PACKAGE_PIN P36 [get_ports clkin6_n]
set_property IOSTANDARD LVDS [get_ports clkin6_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports clkin6_p]
set_property DQS_BIAS TRUE [get_ports clkin6_p]
set_property -dict {PACKAGE_PIN AM39} [get_ports clkin8_n]
set_property -dict {PACKAGE_PIN AM38} [get_ports clkin8_p]
set_property -dict {PACKAGE_PIN AK39} [get_ports fpga_refclk_in_n]
set_property -dict {PACKAGE_PIN AK38} [get_ports fpga_refclk_in_p]
set_property -dict {PACKAGE_PIN V39} [get_ports fpga_refclk_in_replica_n]
set_property -dict {PACKAGE_PIN V38} [get_ports fpga_refclk_in_replica_p]
set_property -dict {PACKAGE_PIN AL46} [get_ports {rx_data_n[2]}]
set_property -dict {PACKAGE_PIN AL45} [get_ports {rx_data_p[2]}]
set_property -dict {PACKAGE_PIN AR46} [get_ports {rx_data_n[0]}]
set_property -dict {PACKAGE_PIN AR45} [get_ports {rx_data_p[0]}]
set_property -dict {PACKAGE_PIN AJ46} [get_ports {rx_data_n[3]}]
set_property -dict {PACKAGE_PIN AJ45} [get_ports {rx_data_p[3]}]
set_property -dict {PACKAGE_PIN AN46} [get_ports {rx_data_n[1]}]
set_property -dict {PACKAGE_PIN AN45} [get_ports {rx_data_p[1]}]
set_property -dict {PACKAGE_PIN AT43} [get_ports {tx_data_n[0]}]
set_property -dict {PACKAGE_PIN AT42} [get_ports {tx_data_p[0]}]
set_property -dict {PACKAGE_PIN AM43} [get_ports {tx_data_n[2]}]
set_property -dict {PACKAGE_PIN AM42} [get_ports {tx_data_p[2]}]
set_property -dict {PACKAGE_PIN AP43} [get_ports {tx_data_n[1]}]
set_property -dict {PACKAGE_PIN AP42} [get_ports {tx_data_p[1]}]
set_property -dict {PACKAGE_PIN AL41} [get_ports {tx_data_n[3]}]
set_property -dict {PACKAGE_PIN AL40} [get_ports {tx_data_p[3]}]
set_property IOSTANDARD LVDS [get_ports {fpga_syncin_n[0]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {fpga_syncin_n[0]}]
set_property PACKAGE_PIN AJ32 [get_ports {fpga_syncin_p[0]}]
set_property PACKAGE_PIN AK32 [get_ports {fpga_syncin_n[0]}]
set_property IOSTANDARD LVDS [get_ports {fpga_syncin_p[0]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {fpga_syncin_p[0]}]
set_property -dict {PACKAGE_PIN AL31 IOSTANDARD LVDS} [get_ports {fpga_syncout_n[0]}]
set_property -dict {PACKAGE_PIN AL30 IOSTANDARD LVDS} [get_ports {fpga_syncout_p[0]}]
set_property -dict {PACKAGE_PIN AG32 IOSTANDARD LVCMOS18} [get_ports {gpio[0]}]
set_property -dict {PACKAGE_PIN AG33 IOSTANDARD LVCMOS18} [get_ports {gpio[1]}]
set_property -dict {PACKAGE_PIN N33 IOSTANDARD LVCMOS18} [get_ports {gpio[2]}]
set_property -dict {PACKAGE_PIN M33 IOSTANDARD LVCMOS18} [get_ports {gpio[3]}]
set_property -dict {PACKAGE_PIN AJ35 IOSTANDARD LVCMOS18} [get_ports {gpio[4]}]
set_property -dict {PACKAGE_PIN AJ36 IOSTANDARD LVCMOS18} [get_ports {gpio[5]}]
set_property -dict {PACKAGE_PIN AG31 IOSTANDARD LVCMOS18} [get_ports {gpio[6]}]
set_property -dict {PACKAGE_PIN AH31 IOSTANDARD LVCMOS18} [get_ports {gpio[7]}]
set_property -dict {PACKAGE_PIN AG34 IOSTANDARD LVCMOS18} [get_ports {gpio[8]}]
set_property -dict {PACKAGE_PIN AH35 IOSTANDARD LVCMOS18} [get_ports {gpio[9]}]
set_property -dict {PACKAGE_PIN N35 IOSTANDARD LVCMOS18} [get_ports {gpio[10]}]
set_property -dict {PACKAGE_PIN AJ31 IOSTANDARD LVCMOS18} [get_ports hmc_gpio1]
set_property -dict {PACKAGE_PIN AP37 IOSTANDARD LVCMOS18} [get_ports hmc_sync]
set_property -dict {PACKAGE_PIN AK29 IOSTANDARD LVCMOS18} [get_ports {irqb[0]}]
set_property -dict {PACKAGE_PIN AK30 IOSTANDARD LVCMOS18} [get_ports {irqb[1]}]
set_property -dict {PACKAGE_PIN AP36 IOSTANDARD LVCMOS18} [get_ports rstb]
set_property -dict {PACKAGE_PIN AP35 IOSTANDARD LVCMOS18} [get_ports {rxen[0]}]
set_property -dict {PACKAGE_PIN AR35 IOSTANDARD LVCMOS18} [get_ports {rxen[1]}]
set_property -dict {PACKAGE_PIN AP38 IOSTANDARD LVCMOS18} [get_ports spi0_csb]
set_property -dict {PACKAGE_PIN AR38 IOSTANDARD LVCMOS18} [get_ports spi0_miso]
set_property -dict {PACKAGE_PIN AR37 IOSTANDARD LVCMOS18} [get_ports spi0_mosi]
set_property -dict {PACKAGE_PIN AT37 IOSTANDARD LVCMOS18} [get_ports spi0_sclk]
set_property -dict {PACKAGE_PIN AH33 IOSTANDARD LVCMOS18} [get_ports spi1_csb]
set_property -dict {PACKAGE_PIN AJ30 IOSTANDARD LVCMOS18} [get_ports spi1_sclk]
set_property -dict {PACKAGE_PIN AH34 IOSTANDARD LVCMOS18} [get_ports spi1_sdio]
set_property IOSTANDARD LVDS [get_ports sysref2_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports sysref2_n]
set_property DQS_BIAS TRUE [get_ports sysref2_n]
set_property PACKAGE_PIN AL32 [get_ports sysref2_p]
set_property PACKAGE_PIN AM32 [get_ports sysref2_n]
set_property IOSTANDARD LVDS [get_ports sysref2_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports sysref2_p]
set_property DQS_BIAS TRUE [get_ports sysref2_p]
set_property -dict {PACKAGE_PIN AJ33 IOSTANDARD LVCMOS18} [get_ports {txen[0]}]
set_property -dict {PACKAGE_PIN AK33 IOSTANDARD LVCMOS18} [get_ports {txen[1]}]

set_property PACKAGE_PIN AK35 [get_ports vadj_1v8_pgood]
set_property IOSTANDARD LVCMOS18 [get_ports vadj_1v8_pgood]
set_property PULLTYPE PULLUP [get_ports vadj_1v8_pgood]

# U145 QSFP+ Module
set_property -dict {LOC Y2} [get_ports {qsfp_rx_p[0]}]
set_property -dict {LOC Y1} [get_ports {qsfp_rx_n[0]}]
set_property -dict {LOC V7} [get_ports {qsfp_tx_p[0]}]
set_property -dict {LOC V6} [get_ports {qsfp_tx_n[0]}]
set_property -dict {LOC W4} [get_ports {qsfp_rx_p[1]}]
set_property -dict {LOC W3} [get_ports {qsfp_rx_n[1]}]
set_property -dict {LOC T7} [get_ports {qsfp_tx_p[1]}]
set_property -dict {LOC T6} [get_ports {qsfp_tx_n[1]}]
set_property -dict {LOC V2} [get_ports {qsfp_rx_p[2]}]
set_property -dict {LOC V1} [get_ports {qsfp_rx_n[2]}]
set_property -dict {LOC P7} [get_ports {qsfp_tx_p[2]}]
set_property -dict {LOC P6} [get_ports {qsfp_tx_n[2]}]
set_property -dict {LOC U4} [get_ports {qsfp_rx_p[3]}]
set_property -dict {LOC U3} [get_ports {qsfp_rx_n[3]}]
set_property -dict {LOC M7} [get_ports {qsfp_tx_p[3]}]
set_property -dict {LOC M6} [get_ports {qsfp_tx_n[3]}]

# REF clock
set_property -dict {LOC W9} [get_ports qsfp_mgt_refclk_p]
set_property -dict {LOC W8} [get_ports qsfp_mgt_refclk_n]

set_property -dict {LOC AM21 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports qsfp_modsell]
set_property -dict {LOC BA22 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports qsfp_resetl]
set_property PACKAGE_PIN AL21 [get_ports qsfp_modprsl]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_modprsl]
set_property PULLTYPE PULLUP [get_ports qsfp_modprsl]
set_property PACKAGE_PIN AP21 [get_ports qsfp_intl]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_intl]
set_property PULLTYPE PULLUP [get_ports qsfp_intl]
set_property -dict {LOC AN21 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports qsfp_lpmode]

# 156.25 MHz MGT reference clock
create_clock -period 6.400 -name qsfp_mgt_refclk [get_ports qsfp_mgt_refclk_p]

set_false_path -to [get_ports {qsfp_modsell qsfp_resetl qsfp_lpmode}]
set_output_delay 0.000 [get_ports {qsfp_modsell qsfp_resetl qsfp_lpmode}]
set_false_path -from [get_ports {qsfp_modprsl qsfp_intl}]
set_input_delay 0.000 [get_ports {qsfp_modprsl qsfp_intl}]

# QSPI flash
set_property -dict {LOC AM19 IOSTANDARD LVCMOS18 DRIVE 12} [get_ports {qspi1_dq[0]}]
set_property -dict {LOC AM18 IOSTANDARD LVCMOS18 DRIVE 12} [get_ports {qspi1_dq[1]}]
set_property -dict {LOC AN20 IOSTANDARD LVCMOS18 DRIVE 12} [get_ports {qspi1_dq[2]}]
set_property -dict {LOC AP20 IOSTANDARD LVCMOS18 DRIVE 12} [get_ports {qspi1_dq[3]}]
set_property -dict {LOC BF16 IOSTANDARD LVCMOS18 DRIVE 12} [get_ports qspi1_cs]

set_false_path -to [get_ports {{qspi1_dq[*]} qspi1_cs}]
set_output_delay 0.000 [get_ports {{qspi1_dq[*]} qspi1_cs}]
set_false_path -from [get_ports qspi1_dq]
set_input_delay 0.000 [get_ports qspi1_dq]



