###############################################################################
## Copyright (C) 2023 Analog Devices, Inc. All rights reserved.
### SPDX short identifier: ADIBSD
###############################################################################

#adrv9026

set_property -dict {PACKAGE_PIN M15} [get_ports ref_clk_p]
set_property -dict {PACKAGE_PIN M14} [get_ports ref_clk_n]
set_property -dict {PACKAGE_PIN AV23 IOSTANDARD LVDS15} [get_ports core_clk_p]
set_property -dict {PACKAGE_PIN AW23 IOSTANDARD LVDS15} [get_ports core_clk_n]

set_property -dict {PACKAGE_PIN AB2} [get_ports {rx_data_p[0]}]
set_property -dict {PACKAGE_PIN AB1} [get_ports {rx_data_n[0]}]
set_property -dict {PACKAGE_PIN AA4} [get_ports {rx_data_p[1]}]
set_property -dict {PACKAGE_PIN AA3} [get_ports {rx_data_n[1]}]
set_property -dict {PACKAGE_PIN Y2} [get_ports {rx_data_p[2]}]
set_property -dict {PACKAGE_PIN Y1} [get_ports {rx_data_n[2]}]
set_property -dict {PACKAGE_PIN W4} [get_ports {rx_data_p[3]}]
set_property -dict {PACKAGE_PIN W3} [get_ports {rx_data_n[3]}]

set_property -dict {PACKAGE_PIN AB7} [get_ports {tx_data_p[0]}]
set_property -dict {PACKAGE_PIN AB6} [get_ports {tx_data_n[0]}]
set_property -dict {PACKAGE_PIN AA9} [get_ports {tx_data_p[1]}]
set_property -dict {PACKAGE_PIN AA8} [get_ports {tx_data_n[1]}]
set_property -dict {PACKAGE_PIN Y7} [get_ports {tx_data_p[2]}]
set_property -dict {PACKAGE_PIN Y6} [get_ports {tx_data_n[2]}]
set_property -dict {PACKAGE_PIN W9} [get_ports {tx_data_p[3]}]
set_property -dict {PACKAGE_PIN W8} [get_ports {tx_data_n[3]}]

set_property -dict {PACKAGE_PIN AV22 IOSTANDARD LVDS15} [get_ports rx_sync_p]
set_property -dict {PACKAGE_PIN AW21 IOSTANDARD LVDS15} [get_ports rx_sync_n]
set_property -dict {PACKAGE_PIN BF16 IOSTANDARD LVDS15} [get_ports rx_os_sync_p]
set_property -dict {PACKAGE_PIN BG16 IOSTANDARD LVDS15} [get_ports rx_os_sync_n]

set_property PACKAGE_PIN BD23 [get_ports sysref_p]
set_property PACKAGE_PIN BD24 [get_ports sysref_n]

set_property PACKAGE_PIN AW24 [get_ports tx_sync_p]
set_property PACKAGE_PIN AY25 [get_ports tx_sync_n]
set_property PACKAGE_PIN BA20 [get_ports tx_sync_1_p]
set_property PACKAGE_PIN BA19 [get_ports tx_sync_1_n]

set_property -dict {PACKAGE_PIN BF19 IOSTANDARD LVCMOS15} [get_ports ad9528_reset_b]
set_property -dict {PACKAGE_PIN BG19 IOSTANDARD LVCMOS15} [get_ports ad9528_sysref_req]
set_property -dict {PACKAGE_PIN BF24 IOSTANDARD LVCMOS15} [get_ports adrv9026_test]

set_property -dict {PACKAGE_PIN BC20 IOSTANDARD LVCMOS15} [get_ports adrv9026_orx_ctrl_a]
set_property -dict {PACKAGE_PIN BD20 IOSTANDARD LVCMOS15} [get_ports adrv9026_orx_ctrl_b]
set_property -dict {PACKAGE_PIN BC18 IOSTANDARD LVCMOS15} [get_ports adrv9026_orx_ctrl_c]
set_property -dict {PACKAGE_PIN BG24 IOSTANDARD LVCMOS15} [get_ports adrv9026_orx_ctrl_d]

set_property -dict {PACKAGE_PIN BE20 IOSTANDARD LVCMOS15} [get_ports adrv9026_rx1_enable]
set_property -dict {PACKAGE_PIN AU23 IOSTANDARD LVCMOS15} [get_ports adrv9026_rx2_enable]
set_property -dict {PACKAGE_PIN BB19 IOSTANDARD LVCMOS15} [get_ports adrv9026_rx3_enable]
set_property -dict {PACKAGE_PIN BB20 IOSTANDARD LVCMOS15} [get_ports adrv9026_rx4_enable]

set_property -dict {PACKAGE_PIN BE21 IOSTANDARD LVCMOS15} [get_ports adrv9026_tx1_enable]
set_property -dict {PACKAGE_PIN AU24 IOSTANDARD LVCMOS15} [get_ports adrv9026_tx2_enable]
set_property -dict {PACKAGE_PIN BD18 IOSTANDARD LVCMOS15} [get_ports adrv9026_tx3_enable]
set_property -dict {PACKAGE_PIN BG25 IOSTANDARD LVCMOS15} [get_ports adrv9026_tx4_enable]

set_property -dict {PACKAGE_PIN AV21 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpint1]
set_property -dict {PACKAGE_PIN BB18 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpint2]
set_property -dict {PACKAGE_PIN AU21 IOSTANDARD LVCMOS15} [get_ports adrv9026_reset_b]

set_property -dict {PACKAGE_PIN AY22 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_00]
set_property -dict {PACKAGE_PIN AY23 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_01]
set_property -dict {PACKAGE_PIN BF21 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_02]
set_property -dict {PACKAGE_PIN BG20 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_03]
set_property -dict {PACKAGE_PIN BE19 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_04]
set_property -dict {PACKAGE_PIN BD19 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_05]
set_property -dict {PACKAGE_PIN BE17 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_06]
set_property -dict {PACKAGE_PIN BD17 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_07]
set_property -dict {PACKAGE_PIN BG18 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_08]
set_property -dict {PACKAGE_PIN BA17 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_09]
set_property -dict {PACKAGE_PIN BA16 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_10]
set_property -dict {PACKAGE_PIN BE16 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_11]
set_property -dict {PACKAGE_PIN BF17 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_12]
set_property -dict {PACKAGE_PIN AM20 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_13]
set_property -dict {PACKAGE_PIN AM21 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_14]
set_property -dict {PACKAGE_PIN BF18 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_15]
set_property -dict {PACKAGE_PIN BF22 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_16]
set_property -dict {PACKAGE_PIN BG21 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_17]
set_property -dict {PACKAGE_PIN BG23 IOSTANDARD LVCMOS15} [get_ports adrv9026_gpio_18]

set_property -dict {PACKAGE_PIN BE25 IOSTANDARD LVCMOS15} [get_ports spi_csn_adrv9026]
set_property -dict {PACKAGE_PIN BE24 IOSTANDARD LVCMOS15} [get_ports spi_csn_ad9528]
set_property -dict {PACKAGE_PIN BC25 IOSTANDARD LVCMOS15} [get_ports spi_clk]
set_property -dict {PACKAGE_PIN BC22 IOSTANDARD LVCMOS15} [get_ports spi_miso]
set_property -dict {PACKAGE_PIN BD25 IOSTANDARD LVCMOS15} [get_ports spi_mosi]


set_property IOSTANDARD LVDS15 [get_ports sysref_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports sysref_p]
set_property IOSTANDARD LVDS15 [get_ports sysref_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports sysref_n]
set_property IOSTANDARD LVDS15 [get_ports tx_sync_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_p]
set_property IOSTANDARD LVDS15 [get_ports tx_sync_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_n]
set_property IOSTANDARD LVDS15 [get_ports tx_sync_1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_1_p]
set_property IOSTANDARD LVDS15 [get_ports tx_sync_1_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_1_n]

set_property PACKAGE_PIN BE39 [get_ports {gpio_bd_i[12]}]
set_property PACKAGE_PIN BE40 [get_ports {gpio_bd_i[11]}]
set_property PACKAGE_PIN BG36 [get_ports {gpio_bd_i[10]}]
set_property PACKAGE_PIN BF37 [get_ports {gpio_bd_i[9]}]
set_property PACKAGE_PIN BF38 [get_ports {gpio_bd_i[8]}]
set_property PACKAGE_PIN BE37 [get_ports {gpio_bd_i[7]}]
set_property PACKAGE_PIN BF36 [get_ports {gpio_bd_i[6]}]
set_property PACKAGE_PIN BE36 [get_ports {gpio_bd_i[5]}]
set_property PACKAGE_PIN BG39 [get_ports {gpio_bd_i[4]}]
set_property PACKAGE_PIN BG40 [get_ports {gpio_bd_i[3]}]
set_property PACKAGE_PIN BD38 [get_ports {gpio_bd_i[2]}]
set_property PACKAGE_PIN BD39 [get_ports {gpio_bd_i[1]}]
set_property PACKAGE_PIN BC40 [get_ports {gpio_bd_i[0]}]
set_property PACKAGE_PIN BG38 [get_ports {gpio_bd_o[7]}]
set_property PACKAGE_PIN BF39 [get_ports {gpio_bd_o[6]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_o[7]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_o[6]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_o[5]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_o[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_o[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_o[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_o[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_o[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[12]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[11]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[10]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[9]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[8]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[7]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[6]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[5]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_bd_i[0]}]
set_property PACKAGE_PIN BC35 [get_ports {gpio_bd_o[5]}]
set_property PACKAGE_PIN BC36 [get_ports {gpio_bd_o[4]}]
set_property PACKAGE_PIN BC37 [get_ports {gpio_bd_o[3]}]
set_property PACKAGE_PIN BC38 [get_ports {gpio_bd_o[2]}]
set_property PACKAGE_PIN BB35 [get_ports {gpio_bd_o[1]}]
set_property PACKAGE_PIN BB36 [get_ports {gpio_bd_o[0]}]
