###############################################################################
## Copyright (C) 2019-2023 Analog Devices, Inc. All rights reserved.
### SPDX short identifier: ADIBSD
###############################################################################

set_property PACKAGE_PIN G24 [get_ports {ddr4_rtl_1_adr[0]}]
set_property PACKAGE_PIN G25 [get_ports {ddr4_rtl_1_adr[1]}]
set_property PACKAGE_PIN G20 [get_ports {ddr4_rtl_1_adr[2]}]
set_property PACKAGE_PIN G21 [get_ports {ddr4_rtl_1_adr[3]}]
set_property PACKAGE_PIN J24 [get_ports {ddr4_rtl_1_adr[4]}]
set_property PACKAGE_PIN H24 [get_ports {ddr4_rtl_1_adr[5]}]
set_property PACKAGE_PIN J21 [get_ports {ddr4_rtl_1_adr[6]}]
set_property PACKAGE_PIN H21 [get_ports {ddr4_rtl_1_adr[7]}]
set_property PACKAGE_PIN J22 [get_ports {ddr4_rtl_1_adr[8]}]
set_property PACKAGE_PIN H22 [get_ports {ddr4_rtl_1_adr[9]}]
set_property PACKAGE_PIN J20 [get_ports {ddr4_rtl_1_adr[10]}]
set_property PACKAGE_PIN N21 [get_ports {ddr4_rtl_1_adr[11]}]
set_property PACKAGE_PIN M21 [get_ports {ddr4_rtl_1_adr[12]}]
set_property PACKAGE_PIN K23 [get_ports {ddr4_rtl_1_adr[13]}]
set_property PACKAGE_PIN K24 [get_ports {ddr4_rtl_1_adr[14]}]
set_property PACKAGE_PIN L21 [get_ports {ddr4_rtl_1_adr[15]}]
set_property PACKAGE_PIN M20 [get_ports {ddr4_rtl_1_adr[16]}]
set_property PACKAGE_PIN E20 [get_ports {ddr4_rtl_1_dq[0]}]
set_property PACKAGE_PIN D16 [get_ports {ddr4_rtl_1_dq[1]}]
set_property PACKAGE_PIN G18 [get_ports {ddr4_rtl_1_dq[2]}]
set_property PACKAGE_PIN E17 [get_ports {ddr4_rtl_1_dq[3]}]
set_property PACKAGE_PIN G19 [get_ports {ddr4_rtl_1_dq[4]}]
set_property PACKAGE_PIN F18 [get_ports {ddr4_rtl_1_dq[5]}]
set_property PACKAGE_PIN F20 [get_ports {ddr4_rtl_1_dq[6]}]
set_property PACKAGE_PIN D17 [get_ports {ddr4_rtl_1_dq[7]}]
set_property PACKAGE_PIN B19 [get_ports {ddr4_rtl_1_dq[8]}]
set_property PACKAGE_PIN A16 [get_ports {ddr4_rtl_1_dq[9]}]
set_property PACKAGE_PIN B20 [get_ports {ddr4_rtl_1_dq[10]}]
set_property PACKAGE_PIN C17 [get_ports {ddr4_rtl_1_dq[11]}]
set_property PACKAGE_PIN A20 [get_ports {ddr4_rtl_1_dq[12]}]
set_property PACKAGE_PIN B16 [get_ports {ddr4_rtl_1_dq[13]}]
set_property PACKAGE_PIN B18 [get_ports {ddr4_rtl_1_dq[14]}]
set_property PACKAGE_PIN C16 [get_ports {ddr4_rtl_1_dq[15]}]
set_property PACKAGE_PIN B25 [get_ports {ddr4_rtl_1_dq[16]}]
set_property PACKAGE_PIN C21 [get_ports {ddr4_rtl_1_dq[17]}]
set_property PACKAGE_PIN B24 [get_ports {ddr4_rtl_1_dq[18]}]
set_property PACKAGE_PIN C22 [get_ports {ddr4_rtl_1_dq[19]}]
set_property PACKAGE_PIN B26 [get_ports {ddr4_rtl_1_dq[20]}]
set_property PACKAGE_PIN A21 [get_ports {ddr4_rtl_1_dq[21]}]
set_property PACKAGE_PIN B21 [get_ports {ddr4_rtl_1_dq[23]}]
set_property PACKAGE_PIN B23 [get_ports {ddr4_rtl_1_dq[22]}]
set_property PACKAGE_PIN E23 [get_ports {ddr4_rtl_1_dq[24]}]
set_property PACKAGE_PIN F21 [get_ports {ddr4_rtl_1_dq[25]}]
set_property PACKAGE_PIN F23 [get_ports {ddr4_rtl_1_dq[26]}]
set_property PACKAGE_PIN F22 [get_ports {ddr4_rtl_1_dq[27]}]
set_property PACKAGE_PIN E25 [get_ports {ddr4_rtl_1_dq[28]}]
set_property PACKAGE_PIN D22 [get_ports {ddr4_rtl_1_dq[29]}]
set_property PACKAGE_PIN F25 [get_ports {ddr4_rtl_1_dq[30]}]
set_property PACKAGE_PIN D21 [get_ports {ddr4_rtl_1_dq[31]}]
set_property PACKAGE_PIN E19 [get_ports {ddr4_rtl_1_dqs_t[0]}]
set_property PACKAGE_PIN A18 [get_ports {ddr4_rtl_1_dqs_t[1]}]
set_property PACKAGE_PIN A25 [get_ports {ddr4_rtl_1_dqs_t[2]}]
set_property PACKAGE_PIN D24 [get_ports {ddr4_rtl_1_dqs_t[3]}]
set_property PACKAGE_PIN L22 [get_ports {ddr4_rtl_1_ba[0]}]
set_property PACKAGE_PIN L23 [get_ports {ddr4_rtl_1_ba[1]}]
set_property PACKAGE_PIN L20 [get_ports {ddr4_rtl_1_bg[0]}]
set_property PACKAGE_PIN N22 [get_ports {ddr4_rtl_1_ck_t[0]}]
set_property PACKAGE_PIN D25 [get_ports {ddr4_rtl_1_odt[0]}]
set_property PACKAGE_PIN F17 [get_ports {ddr4_rtl_1_dm_n[0]}]
set_property PACKAGE_PIN C19 [get_ports {ddr4_rtl_1_dm_n[1]}]
set_property PACKAGE_PIN A22 [get_ports {ddr4_rtl_1_dm_n[2]}]
set_property PACKAGE_PIN E24 [get_ports {ddr4_rtl_1_dm_n[3]}]
set_property PACKAGE_PIN A23 [get_ports {ddr4_rtl_1_cs_n[0]}]
set_property PACKAGE_PIN E22 [get_ports ddr4_rtl_1_act_n]
set_property PACKAGE_PIN K22 [get_ports {ddr4_rtl_1_cke[0]}]
set_property PACKAGE_PIN D20 [get_ports ddr4_rtl_1_reset_n]

set_property -dict {PACKAGE_PIN H23 IOSTANDARD LVDS} [get_ports ddr4_ref_1_clk_p]
set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVCMOS12} [get_ports ddr4_rtl_1_par]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS12} [get_ports ddr4_rtl_1_alert_n]
