
# create board design
# interface ports

create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddrx_rtl:1.0 ddr
create_bd_intf_port -mode Master -vlnv xilinx.com:display_processing_system7:fixedio_rtl:1.0 fixed_io

# create_bd_port -dir O spi0_csn_2_o
# create_bd_port -dir O spi0_csn_1_o
# create_bd_port -dir O spi0_csn_0_o
# create_bd_port -dir I spi0_csn_i
# create_bd_port -dir I spi0_clk_i
# create_bd_port -dir O spi0_clk_o
# create_bd_port -dir I spi0_sdo_i
# create_bd_port -dir O spi0_sdo_o
# create_bd_port -dir I spi0_sdi_i

# create_bd_port -dir O spi1_csn_2_o
# create_bd_port -dir O spi1_csn_1_o
# create_bd_port -dir O spi1_csn_0_o
# create_bd_port -dir I spi1_csn_i
# create_bd_port -dir I spi1_clk_i
# create_bd_port -dir O spi1_clk_o
# create_bd_port -dir I spi1_sdo_i
# create_bd_port -dir O spi1_sdo_o
# create_bd_port -dir I spi1_sdi_i

create_bd_port -dir I -from 63 -to 0 gpio_i
create_bd_port -dir O -from 63 -to 0 gpio_o
create_bd_port -dir O -from 63 -to 0 gpio_t


# instance: sys_ps7

ad_ip_instance processing_system7 sys_ps7 [list \
   PCW_ACT_APU_PERIPHERAL_FREQMHZ {650.000000} \
   PCW_ACT_CAN_PERIPHERAL_FREQMHZ {10.000000} \
   PCW_ACT_DCI_PERIPHERAL_FREQMHZ {10.096154} \
   PCW_ACT_ENET0_PERIPHERAL_FREQMHZ {125.000000} \
   PCW_ACT_ENET1_PERIPHERAL_FREQMHZ {10.000000} \
   PCW_ACT_FPGA0_PERIPHERAL_FREQMHZ {100.000000} \
   PCW_ACT_FPGA1_PERIPHERAL_FREQMHZ {200.000000} \
   PCW_ACT_FPGA2_PERIPHERAL_FREQMHZ {10.000000} \
   PCW_ACT_FPGA3_PERIPHERAL_FREQMHZ {10.000000} \
   PCW_ACT_I2C_PERIPHERAL_FREQMHZ {50} \
   PCW_ACT_PCAP_PERIPHERAL_FREQMHZ {200.000000} \
   PCW_ACT_QSPI_PERIPHERAL_FREQMHZ {10.000000} \
   PCW_ACT_SDIO_PERIPHERAL_FREQMHZ {50.000000} \
   PCW_ACT_SMC_PERIPHERAL_FREQMHZ {10.000000} \
   PCW_ACT_SPI_PERIPHERAL_FREQMHZ {166.666672} \
   PCW_ACT_TPIU_PERIPHERAL_FREQMHZ {200.000000} \
   PCW_ACT_TTC0_CLK0_PERIPHERAL_FREQMHZ {108.333336} \
   PCW_ACT_TTC0_CLK1_PERIPHERAL_FREQMHZ {108.333336} \
   PCW_ACT_TTC0_CLK2_PERIPHERAL_FREQMHZ {108.333336} \
   PCW_ACT_TTC1_CLK0_PERIPHERAL_FREQMHZ {108.333336} \
   PCW_ACT_TTC1_CLK1_PERIPHERAL_FREQMHZ {108.333336} \
   PCW_ACT_TTC1_CLK2_PERIPHERAL_FREQMHZ {108.333336} \
   PCW_ACT_TTC_PERIPHERAL_FREQMHZ {50} \
   PCW_ACT_UART_PERIPHERAL_FREQMHZ {100.000000} \
   PCW_ACT_USB0_PERIPHERAL_FREQMHZ {60} \
   PCW_ACT_USB1_PERIPHERAL_FREQMHZ {60} \
   PCW_ACT_WDT_PERIPHERAL_FREQMHZ {108.333336} \
   PCW_APU_CLK_RATIO_ENABLE {6:2:1} \
   PCW_APU_PERIPHERAL_FREQMHZ {650} \
   PCW_ARMPLL_CTRL_FBDIV {26} \
   PCW_CAN0_BASEADDR {0xE0008000} \
   PCW_CAN0_CAN0_IO {<Select>} \
   PCW_CAN0_GRP_CLK_ENABLE {0} \
   PCW_CAN0_GRP_CLK_IO {<Select>} \
   PCW_CAN0_HIGHADDR {0xE0008FFF} \
   PCW_CAN0_PERIPHERAL_CLKSRC {External} \
   PCW_CAN0_PERIPHERAL_ENABLE {0} \
   PCW_CAN0_PERIPHERAL_FREQMHZ {-1} \
   PCW_CAN1_BASEADDR {0xE0009000} \
   PCW_CAN1_CAN1_IO {<Select>} \
   PCW_CAN1_GRP_CLK_ENABLE {0} \
   PCW_CAN1_GRP_CLK_IO {<Select>} \
   PCW_CAN1_HIGHADDR {0xE0009FFF} \
   PCW_CAN1_PERIPHERAL_CLKSRC {External} \
   PCW_CAN1_PERIPHERAL_ENABLE {0} \
   PCW_CAN1_PERIPHERAL_FREQMHZ {-1} \
   PCW_CAN_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_CAN_PERIPHERAL_DIVISOR0 {1} \
   PCW_CAN_PERIPHERAL_DIVISOR1 {1} \
   PCW_CAN_PERIPHERAL_FREQMHZ {100} \
   PCW_CAN_PERIPHERAL_VALID {0} \
   PCW_CLK0_FREQ {100000000} \
   PCW_CLK1_FREQ {10000000} \
   PCW_CLK2_FREQ {10000000} \
   PCW_CLK3_FREQ {10000000} \
   PCW_CORE0_FIQ_INTR {0} \
   PCW_CORE0_IRQ_INTR {0} \
   PCW_CORE1_FIQ_INTR {0} \
   PCW_CORE1_IRQ_INTR {0} \
   PCW_CPU_CPU_6X4X_MAX_RANGE {667} \
   PCW_CPU_CPU_PLL_FREQMHZ {1300.000} \
   PCW_CPU_PERIPHERAL_CLKSRC {ARM PLL} \
   PCW_CPU_PERIPHERAL_DIVISOR0 {2} \
   PCW_CRYSTAL_PERIPHERAL_FREQMHZ {50} \
   PCW_DCI_PERIPHERAL_CLKSRC {DDR PLL} \
   PCW_DCI_PERIPHERAL_DIVISOR0 {52} \
   PCW_DCI_PERIPHERAL_DIVISOR1 {2} \
   PCW_DCI_PERIPHERAL_FREQMHZ {10.159} \
   PCW_DDRPLL_CTRL_FBDIV {21} \
   PCW_DDR_DDR_PLL_FREQMHZ {1050.000} \
   PCW_DDR_HPRLPR_QUEUE_PARTITION {HPR(0)/LPR(32)} \
   PCW_DDR_HPR_TO_CRITICAL_PRIORITY_LEVEL {15} \
   PCW_DDR_LPR_TO_CRITICAL_PRIORITY_LEVEL {2} \
   PCW_DDR_PERIPHERAL_CLKSRC {DDR PLL} \
   PCW_DDR_PERIPHERAL_DIVISOR0 {2} \
   PCW_DDR_PORT0_HPR_ENABLE {1} \
   PCW_DDR_PORT1_HPR_ENABLE {0} \
   PCW_DDR_PORT2_HPR_ENABLE {0} \
   PCW_DDR_PORT3_HPR_ENABLE {0} \
   PCW_DDR_PRIORITY_READPORT_0 {EMIO} \
   PCW_DDR_PRIORITY_READPORT_1 {<Select>} \
   PCW_DDR_PRIORITY_READPORT_2 {<Select>} \
   PCW_DDR_PRIORITY_READPORT_3 {<Select>} \
   PCW_DDR_PRIORITY_WRITEPORT_0 {EMIO} \
   PCW_DDR_PRIORITY_WRITEPORT_1 {<Select>} \
   PCW_DDR_PRIORITY_WRITEPORT_2 {<Select>} \
   PCW_DDR_PRIORITY_WRITEPORT_3 {<Select>} \
   PCW_DDR_RAM_BASEADDR {0x00100000} \
   PCW_DDR_RAM_HIGHADDR {0x1FFFFFFF} \
   PCW_DDR_WRITE_TO_CRITICAL_PRIORITY_LEVEL {2} \
   PCW_DM_WIDTH {4} \
   PCW_DQS_WIDTH {4} \
   PCW_DQ_WIDTH {32} \
   PCW_ENET0_BASEADDR {0xE000B000} \
   PCW_ENET0_ENET0_IO {MIO 16 .. 27} \
   PCW_ENET0_GRP_MDIO_ENABLE {1} \
   PCW_ENET0_GRP_MDIO_IO {MIO 52 .. 53} \
   PCW_ENET0_HIGHADDR {0xE000BFFF} \
   PCW_ENET0_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_ENET0_PERIPHERAL_DIVISOR0 {8} \
   PCW_ENET0_PERIPHERAL_DIVISOR1 {1} \
   PCW_ENET0_PERIPHERAL_ENABLE {1} \
   PCW_ENET0_PERIPHERAL_FREQMHZ {1000 Mbps} \
   PCW_ENET0_RESET_ENABLE {1} \
   PCW_ENET0_RESET_IO {MIO 9} \
   PCW_ENET1_BASEADDR {0xE000C000} \
   PCW_ENET1_ENET1_IO {<Select>} \
   PCW_ENET1_GRP_MDIO_ENABLE {0} \
   PCW_ENET1_GRP_MDIO_IO {<Select>} \
   PCW_ENET1_HIGHADDR {0xE000CFFF} \
   PCW_ENET1_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_ENET1_PERIPHERAL_DIVISOR0 {1} \
   PCW_ENET1_PERIPHERAL_DIVISOR1 {1} \
   PCW_ENET1_PERIPHERAL_ENABLE {0} \
   PCW_ENET1_PERIPHERAL_FREQMHZ {1000 Mbps} \
   PCW_ENET1_RESET_ENABLE {0} \
   PCW_ENET1_RESET_IO {<Select>} \
   PCW_ENET_RESET_ENABLE {1} \
   PCW_ENET_RESET_POLARITY {Active Low} \
   PCW_ENET_RESET_SELECT {Share reset pin} \
   PCW_EN_4K_TIMER {0} \
   PCW_EN_CAN0 {0} \
   PCW_EN_CAN1 {0} \
   PCW_EN_CLK0_PORT {1} \
   PCW_EN_CLK1_PORT {1} \
   PCW_EN_CLK2_PORT {0} \
   PCW_EN_CLK3_PORT {0} \
   PCW_EN_CLKTRIG0_PORT {0} \
   PCW_EN_CLKTRIG1_PORT {0} \
   PCW_EN_CLKTRIG2_PORT {0} \
   PCW_EN_CLKTRIG3_PORT {0} \
   PCW_EN_DDR {1} \
   PCW_EN_EMIO_CAN0 {0} \
   PCW_EN_EMIO_CAN1 {0} \
   PCW_EN_EMIO_CD_SDIO0 {0} \
   PCW_EN_EMIO_CD_SDIO1 {0} \
   PCW_EN_EMIO_ENET0 {0} \
   PCW_EN_EMIO_ENET1 {0} \
   PCW_EN_EMIO_GPIO {0} \
   PCW_EN_EMIO_I2C0 {1} \
   PCW_EN_EMIO_I2C1 {0} \
   PCW_EN_EMIO_MODEM_UART0 {0} \
   PCW_EN_EMIO_MODEM_UART1 {0} \
   PCW_EN_EMIO_PJTAG {0} \
   PCW_EN_EMIO_SDIO0 {0} \
   PCW_EN_EMIO_SDIO1 {0} \
   PCW_EN_EMIO_SPI0 {0} \
   PCW_EN_EMIO_SPI1 {0} \
   PCW_EN_EMIO_SRAM_INT {0} \
   PCW_EN_EMIO_TRACE {0} \
   PCW_EN_EMIO_TTC0 {0} \
   PCW_EN_EMIO_TTC1 {0} \
   PCW_EN_EMIO_UART0 {0} \
   PCW_EN_EMIO_UART1 {0} \
   PCW_EN_EMIO_WDT {0} \
   PCW_EN_EMIO_WP_SDIO0 {0} \
   PCW_EN_EMIO_WP_SDIO1 {0} \
   PCW_EN_ENET0 {1} \
   PCW_EN_ENET1 {0} \
   PCW_EN_GPIO {1} \
   PCW_EN_I2C0 {1} \
   PCW_EN_I2C1 {0} \
   PCW_EN_MODEM_UART0 {0} \
   PCW_EN_MODEM_UART1 {0} \
   PCW_EN_PJTAG {0} \
   PCW_EN_PTP_ENET0 {0} \
   PCW_EN_PTP_ENET1 {0} \
   PCW_EN_QSPI {0} \
   PCW_EN_RST0_PORT {1} \
   PCW_EN_RST1_PORT {1} \
   PCW_EN_RST2_PORT {0} \
   PCW_EN_RST3_PORT {0} \
   PCW_EN_SDIO0 {1} \
   PCW_EN_SDIO1 {0} \
   PCW_EN_SMC {0} \
   PCW_EN_SPI0 {0} \
   PCW_EN_SPI1 {0} \
   PCW_EN_TRACE {0} \
   PCW_EN_TTC0 {0} \
   PCW_EN_TTC1 {0} \
   PCW_EN_UART0 {1} \
   PCW_EN_UART1 {0} \
   PCW_EN_USB0 {1} \
   PCW_EN_USB1 {0} \
   PCW_EN_WDT {0} \
   PCW_FCLK0_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_FCLK0_PERIPHERAL_DIVISOR0 {5} \
   PCW_FCLK0_PERIPHERAL_DIVISOR1 {2} \
   PCW_FCLK1_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_FCLK1_PERIPHERAL_DIVISOR0 {1} \
   PCW_FCLK1_PERIPHERAL_DIVISOR1 {1} \
   PCW_FCLK2_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_FCLK2_PERIPHERAL_DIVISOR0 {1} \
   PCW_FCLK2_PERIPHERAL_DIVISOR1 {1} \
   PCW_FCLK3_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_FCLK3_PERIPHERAL_DIVISOR0 {1} \
   PCW_FCLK3_PERIPHERAL_DIVISOR1 {1} \
   PCW_FCLK_CLK0_BUF {TRUE} \
   PCW_FCLK_CLK1_BUF {FALSE} \
   PCW_FCLK_CLK2_BUF {FALSE} \
   PCW_FCLK_CLK3_BUF {FALSE} \
   PCW_FPGA0_PERIPHERAL_FREQMHZ {100} \
   PCW_FPGA1_PERIPHERAL_FREQMHZ {200} \
   PCW_FPGA2_PERIPHERAL_FREQMHZ {120} \
   PCW_FPGA3_PERIPHERAL_FREQMHZ {50} \
   PCW_FPGA_FCLK0_ENABLE {1} \
   PCW_FPGA_FCLK1_ENABLE {0} \
   PCW_FPGA_FCLK2_ENABLE {0} \
   PCW_FPGA_FCLK3_ENABLE {0} \
   PCW_FTM_CTI_IN0 {<Select>} \
   PCW_FTM_CTI_IN1 {<Select>} \
   PCW_FTM_CTI_IN2 {<Select>} \
   PCW_FTM_CTI_IN3 {<Select>} \
   PCW_FTM_CTI_OUT0 {<Select>} \
   PCW_FTM_CTI_OUT1 {<Select>} \
   PCW_FTM_CTI_OUT2 {<Select>} \
   PCW_FTM_CTI_OUT3 {<Select>} \
   PCW_GP0_EN_MODIFIABLE_TXN {0} \
   PCW_GP0_NUM_READ_THREADS {4} \
   PCW_GP0_NUM_WRITE_THREADS {4} \
   PCW_GP1_EN_MODIFIABLE_TXN {0} \
   PCW_GP1_NUM_READ_THREADS {4} \
   PCW_GP1_NUM_WRITE_THREADS {4} \
   PCW_GPIO_BASEADDR {0xE000A000} \
   PCW_GPIO_EMIO_GPIO_ENABLE {1} \
   PCW_GPIO_EMIO_GPIO_IO {64} \
   PCW_GPIO_EMIO_GPIO_WIDTH {64} \
   PCW_GPIO_HIGHADDR {0xE000AFFF} \
   PCW_GPIO_MIO_GPIO_ENABLE {1} \
   PCW_GPIO_MIO_GPIO_IO {MIO} \
   PCW_GPIO_PERIPHERAL_ENABLE {0} \
   PCW_I2C0_BASEADDR {0xE0004000} \
   PCW_I2C0_GRP_INT_ENABLE {1} \
   PCW_I2C0_GRP_INT_IO {EMIO} \
   PCW_I2C0_HIGHADDR {0xE0004FFF} \
   PCW_I2C0_I2C0_IO {EMIO} \
   PCW_I2C0_PERIPHERAL_ENABLE {1} \
   PCW_I2C0_RESET_ENABLE {0} \
   PCW_I2C0_RESET_IO {<Select>} \
   PCW_I2C1_BASEADDR {0xE0005000} \
   PCW_I2C1_GRP_INT_ENABLE {0} \
   PCW_I2C1_GRP_INT_IO {<Select>} \
   PCW_I2C1_HIGHADDR {0xE0005FFF} \
   PCW_I2C1_I2C1_IO {<Select>} \
   PCW_I2C1_PERIPHERAL_ENABLE {0} \
   PCW_I2C1_RESET_ENABLE {0} \
   PCW_I2C1_RESET_IO {<Select>} \
   PCW_I2C_PERIPHERAL_FREQMHZ {108.333336} \
   PCW_I2C_RESET_ENABLE {1} \
   PCW_I2C_RESET_POLARITY {Active Low} \
   PCW_I2C_RESET_SELECT {Share reset pin} \
   PCW_IMPORT_BOARD_PRESET {None} \
   PCW_INCLUDE_ACP_TRANS_CHECK {0} \
   PCW_INCLUDE_TRACE_BUFFER {0} \
   PCW_IOPLL_CTRL_FBDIV {20} \
   PCW_IO_IO_PLL_FREQMHZ {1000.000} \
   PCW_IRQ_F2P_INTR {1} \
   PCW_IRQ_F2P_MODE {REVERSE} \
   PCW_MIO_0_DIRECTION {inout} \
   PCW_MIO_0_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_0_PULLUP {enabled} \
   PCW_MIO_0_SLEW {slow} \
   PCW_MIO_10_DIRECTION {inout} \
   PCW_MIO_10_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_10_PULLUP {enabled} \
   PCW_MIO_10_SLEW {slow} \
   PCW_MIO_11_DIRECTION {inout} \
   PCW_MIO_11_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_11_PULLUP {enabled} \
   PCW_MIO_11_SLEW {slow} \
   PCW_MIO_12_DIRECTION {inout} \
   PCW_MIO_12_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_12_PULLUP {enabled} \
   PCW_MIO_12_SLEW {slow} \
   PCW_MIO_13_DIRECTION {inout} \
   PCW_MIO_13_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_13_PULLUP {enabled} \
   PCW_MIO_13_SLEW {slow} \
   PCW_MIO_14_DIRECTION {in} \
   PCW_MIO_14_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_14_PULLUP {enabled} \
   PCW_MIO_14_SLEW {slow} \
   PCW_MIO_15_DIRECTION {out} \
   PCW_MIO_15_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_15_PULLUP {enabled} \
   PCW_MIO_15_SLEW {slow} \
   PCW_MIO_16_DIRECTION {out} \
   PCW_MIO_16_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_16_PULLUP {enabled} \
   PCW_MIO_16_SLEW {slow} \
   PCW_MIO_17_DIRECTION {out} \
   PCW_MIO_17_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_17_PULLUP {enabled} \
   PCW_MIO_17_SLEW {slow} \
   PCW_MIO_18_DIRECTION {out} \
   PCW_MIO_18_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_18_PULLUP {enabled} \
   PCW_MIO_18_SLEW {slow} \
   PCW_MIO_19_DIRECTION {out} \
   PCW_MIO_19_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_19_PULLUP {enabled} \
   PCW_MIO_19_SLEW {slow} \
   PCW_MIO_1_DIRECTION {inout} \
   PCW_MIO_1_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_1_PULLUP {enabled} \
   PCW_MIO_1_SLEW {slow} \
   PCW_MIO_20_DIRECTION {out} \
   PCW_MIO_20_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_20_PULLUP {enabled} \
   PCW_MIO_20_SLEW {slow} \
   PCW_MIO_21_DIRECTION {out} \
   PCW_MIO_21_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_21_PULLUP {enabled} \
   PCW_MIO_21_SLEW {slow} \
   PCW_MIO_22_DIRECTION {in} \
   PCW_MIO_22_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_22_PULLUP {enabled} \
   PCW_MIO_22_SLEW {slow} \
   PCW_MIO_23_DIRECTION {in} \
   PCW_MIO_23_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_23_PULLUP {enabled} \
   PCW_MIO_23_SLEW {slow} \
   PCW_MIO_24_DIRECTION {in} \
   PCW_MIO_24_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_24_PULLUP {enabled} \
   PCW_MIO_24_SLEW {slow} \
   PCW_MIO_25_DIRECTION {in} \
   PCW_MIO_25_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_25_PULLUP {enabled} \
   PCW_MIO_25_SLEW {slow} \
   PCW_MIO_26_DIRECTION {in} \
   PCW_MIO_26_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_26_PULLUP {enabled} \
   PCW_MIO_26_SLEW {slow} \
   PCW_MIO_27_DIRECTION {in} \
   PCW_MIO_27_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_27_PULLUP {enabled} \
   PCW_MIO_27_SLEW {slow} \
   PCW_MIO_28_DIRECTION {inout} \
   PCW_MIO_28_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_28_PULLUP {enabled} \
   PCW_MIO_28_SLEW {slow} \
   PCW_MIO_29_DIRECTION {in} \
   PCW_MIO_29_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_29_PULLUP {enabled} \
   PCW_MIO_29_SLEW {slow} \
   PCW_MIO_2_DIRECTION {inout} \
   PCW_MIO_2_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_2_PULLUP {disabled} \
   PCW_MIO_2_SLEW {slow} \
   PCW_MIO_30_DIRECTION {out} \
   PCW_MIO_30_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_30_PULLUP {enabled} \
   PCW_MIO_30_SLEW {slow} \
   PCW_MIO_31_DIRECTION {in} \
   PCW_MIO_31_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_31_PULLUP {enabled} \
   PCW_MIO_31_SLEW {slow} \
   PCW_MIO_32_DIRECTION {inout} \
   PCW_MIO_32_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_32_PULLUP {enabled} \
   PCW_MIO_32_SLEW {slow} \
   PCW_MIO_33_DIRECTION {inout} \
   PCW_MIO_33_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_33_PULLUP {enabled} \
   PCW_MIO_33_SLEW {slow} \
   PCW_MIO_34_DIRECTION {inout} \
   PCW_MIO_34_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_34_PULLUP {enabled} \
   PCW_MIO_34_SLEW {slow} \
   PCW_MIO_35_DIRECTION {inout} \
   PCW_MIO_35_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_35_PULLUP {enabled} \
   PCW_MIO_35_SLEW {slow} \
   PCW_MIO_36_DIRECTION {in} \
   PCW_MIO_36_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_36_PULLUP {enabled} \
   PCW_MIO_36_SLEW {slow} \
   PCW_MIO_37_DIRECTION {inout} \
   PCW_MIO_37_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_37_PULLUP {enabled} \
   PCW_MIO_37_SLEW {slow} \
   PCW_MIO_38_DIRECTION {inout} \
   PCW_MIO_38_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_38_PULLUP {enabled} \
   PCW_MIO_38_SLEW {slow} \
   PCW_MIO_39_DIRECTION {inout} \
   PCW_MIO_39_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_39_PULLUP {enabled} \
   PCW_MIO_39_SLEW {slow} \
   PCW_MIO_3_DIRECTION {inout} \
   PCW_MIO_3_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_3_PULLUP {disabled} \
   PCW_MIO_3_SLEW {slow} \
   PCW_MIO_40_DIRECTION {inout} \
   PCW_MIO_40_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_40_PULLUP {enabled} \
   PCW_MIO_40_SLEW {slow} \
   PCW_MIO_41_DIRECTION {inout} \
   PCW_MIO_41_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_41_PULLUP {enabled} \
   PCW_MIO_41_SLEW {slow} \
   PCW_MIO_42_DIRECTION {inout} \
   PCW_MIO_42_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_42_PULLUP {enabled} \
   PCW_MIO_42_SLEW {slow} \
   PCW_MIO_43_DIRECTION {inout} \
   PCW_MIO_43_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_43_PULLUP {enabled} \
   PCW_MIO_43_SLEW {slow} \
   PCW_MIO_44_DIRECTION {inout} \
   PCW_MIO_44_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_44_PULLUP {enabled} \
   PCW_MIO_44_SLEW {slow} \
   PCW_MIO_45_DIRECTION {inout} \
   PCW_MIO_45_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_45_PULLUP {enabled} \
   PCW_MIO_45_SLEW {slow} \
   PCW_MIO_46_DIRECTION {out} \
   PCW_MIO_46_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_46_PULLUP {enabled} \
   PCW_MIO_46_SLEW {slow} \
   PCW_MIO_47_DIRECTION {in} \
   PCW_MIO_47_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_47_PULLUP {enabled} \
   PCW_MIO_47_SLEW {slow} \
   PCW_MIO_48_DIRECTION {inout} \
   PCW_MIO_48_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_48_PULLUP {enabled} \
   PCW_MIO_48_SLEW {slow} \
   PCW_MIO_49_DIRECTION {inout} \
   PCW_MIO_49_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_49_PULLUP {enabled} \
   PCW_MIO_49_SLEW {slow} \
   PCW_MIO_4_DIRECTION {inout} \
   PCW_MIO_4_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_4_PULLUP {disabled} \
   PCW_MIO_4_SLEW {slow} \
   PCW_MIO_50_DIRECTION {inout} \
   PCW_MIO_50_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_50_PULLUP {enabled} \
   PCW_MIO_50_SLEW {slow} \
   PCW_MIO_51_DIRECTION {inout} \
   PCW_MIO_51_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_51_PULLUP {enabled} \
   PCW_MIO_51_SLEW {slow} \
   PCW_MIO_52_DIRECTION {out} \
   PCW_MIO_52_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_52_PULLUP {enabled} \
   PCW_MIO_52_SLEW {slow} \
   PCW_MIO_53_DIRECTION {inout} \
   PCW_MIO_53_IOTYPE {LVCMOS 1.8V} \
   PCW_MIO_53_PULLUP {enabled} \
   PCW_MIO_53_SLEW {slow} \
   PCW_MIO_5_DIRECTION {inout} \
   PCW_MIO_5_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_5_PULLUP {disabled} \
   PCW_MIO_5_SLEW {slow} \
   PCW_MIO_6_DIRECTION {inout} \
   PCW_MIO_6_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_6_PULLUP {disabled} \
   PCW_MIO_6_SLEW {slow} \
   PCW_MIO_7_DIRECTION {out} \
   PCW_MIO_7_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_7_PULLUP {disabled} \
   PCW_MIO_7_SLEW {slow} \
   PCW_MIO_8_DIRECTION {out} \
   PCW_MIO_8_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_8_PULLUP {disabled} \
   PCW_MIO_8_SLEW {slow} \
   PCW_MIO_9_DIRECTION {out} \
   PCW_MIO_9_IOTYPE {LVCMOS 3.3V} \
   PCW_MIO_9_PULLUP {enabled} \
   PCW_MIO_9_SLEW {slow} \
   PCW_MIO_PRIMITIVE {54} \
   PCW_MIO_TREE_PERIPHERALS {GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#ENET Reset#GPIO#GPIO#GPIO#GPIO#UART 0#UART 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#USB Reset#SD 0#GPIO#GPIO#GPIO#GPIO#Enet 0#Enet 0} \
   PCW_MIO_TREE_SIGNALS {gpio[0]#gpio[1]#gpio[2]#gpio[3]#gpio[4]#gpio[5]#gpio[6]#gpio[7]#gpio[8]#reset#gpio[10]#gpio[11]#gpio[12]#gpio[13]#rx#tx#tx_clk#txd[0]#txd[1]#txd[2]#txd[3]#tx_ctl#rx_clk#rxd[0]#rxd[1]#rxd[2]#rxd[3]#rx_ctl#data[4]#dir#stp#nxt#data[0]#data[1]#data[2]#data[3]#clk#data[5]#data[6]#data[7]#clk#cmd#data[0]#data[1]#data[2]#data[3]#reset#cd#gpio[48]#gpio[49]#gpio[50]#gpio[51]#mdc#mdio} \
   PCW_M_AXI_GP0_ENABLE_STATIC_REMAP {0} \
   PCW_M_AXI_GP0_ID_WIDTH {12} \
   PCW_M_AXI_GP0_SUPPORT_NARROW_BURST {0} \
   PCW_M_AXI_GP0_THREAD_ID_WIDTH {12} \
   PCW_M_AXI_GP1_ENABLE_STATIC_REMAP {0} \
   PCW_M_AXI_GP1_ID_WIDTH {12} \
   PCW_M_AXI_GP1_SUPPORT_NARROW_BURST {0} \
   PCW_M_AXI_GP1_THREAD_ID_WIDTH {12} \
   PCW_NAND_CYCLES_T_AR {1} \
   PCW_NAND_CYCLES_T_CLR {1} \
   PCW_NAND_CYCLES_T_RC {11} \
   PCW_NAND_CYCLES_T_REA {1} \
   PCW_NAND_CYCLES_T_RR {1} \
   PCW_NAND_CYCLES_T_WC {11} \
   PCW_NAND_CYCLES_T_WP {1} \
   PCW_NAND_GRP_D8_ENABLE {0} \
   PCW_NAND_GRP_D8_IO {<Select>} \
   PCW_NAND_NAND_IO {<Select>} \
   PCW_NAND_PERIPHERAL_ENABLE {0} \
   PCW_NOR_CS0_T_CEOE {1} \
   PCW_NOR_CS0_T_PC {1} \
   PCW_NOR_CS0_T_RC {11} \
   PCW_NOR_CS0_T_TR {1} \
   PCW_NOR_CS0_T_WC {11} \
   PCW_NOR_CS0_T_WP {1} \
   PCW_NOR_CS0_WE_TIME {0} \
   PCW_NOR_CS1_T_CEOE {1} \
   PCW_NOR_CS1_T_PC {1} \
   PCW_NOR_CS1_T_RC {11} \
   PCW_NOR_CS1_T_TR {1} \
   PCW_NOR_CS1_T_WC {11} \
   PCW_NOR_CS1_T_WP {1} \
   PCW_NOR_CS1_WE_TIME {0} \
   PCW_NOR_GRP_A25_ENABLE {0} \
   PCW_NOR_GRP_A25_IO {<Select>} \
   PCW_NOR_GRP_CS0_ENABLE {0} \
   PCW_NOR_GRP_CS0_IO {<Select>} \
   PCW_NOR_GRP_CS1_ENABLE {0} \
   PCW_NOR_GRP_CS1_IO {<Select>} \
   PCW_NOR_GRP_SRAM_CS0_ENABLE {0} \
   PCW_NOR_GRP_SRAM_CS0_IO {<Select>} \
   PCW_NOR_GRP_SRAM_CS1_ENABLE {0} \
   PCW_NOR_GRP_SRAM_CS1_IO {<Select>} \
   PCW_NOR_GRP_SRAM_INT_ENABLE {0} \
   PCW_NOR_GRP_SRAM_INT_IO {<Select>} \
   PCW_NOR_NOR_IO {<Select>} \
   PCW_NOR_PERIPHERAL_ENABLE {0} \
   PCW_NOR_SRAM_CS0_T_CEOE {1} \
   PCW_NOR_SRAM_CS0_T_PC {1} \
   PCW_NOR_SRAM_CS0_T_RC {11} \
   PCW_NOR_SRAM_CS0_T_TR {1} \
   PCW_NOR_SRAM_CS0_T_WC {11} \
   PCW_NOR_SRAM_CS0_T_WP {1} \
   PCW_NOR_SRAM_CS0_WE_TIME {0} \
   PCW_NOR_SRAM_CS1_T_CEOE {1} \
   PCW_NOR_SRAM_CS1_T_PC {1} \
   PCW_NOR_SRAM_CS1_T_RC {11} \
   PCW_NOR_SRAM_CS1_T_TR {1} \
   PCW_NOR_SRAM_CS1_T_WC {11} \
   PCW_NOR_SRAM_CS1_T_WP {1} \
   PCW_NOR_SRAM_CS1_WE_TIME {0} \
   PCW_OVERRIDE_BASIC_CLOCK {0} \
   PCW_P2F_CAN0_INTR {0} \
   PCW_P2F_CAN1_INTR {0} \
   PCW_P2F_CTI_INTR {0} \
   PCW_P2F_DMAC0_INTR {0} \
   PCW_P2F_DMAC1_INTR {0} \
   PCW_P2F_DMAC2_INTR {0} \
   PCW_P2F_DMAC3_INTR {0} \
   PCW_P2F_DMAC4_INTR {0} \
   PCW_P2F_DMAC5_INTR {0} \
   PCW_P2F_DMAC6_INTR {0} \
   PCW_P2F_DMAC7_INTR {0} \
   PCW_P2F_DMAC_ABORT_INTR {0} \
   PCW_P2F_ENET0_INTR {0} \
   PCW_P2F_ENET1_INTR {0} \
   PCW_P2F_GPIO_INTR {0} \
   PCW_P2F_I2C0_INTR {0} \
   PCW_P2F_I2C1_INTR {0} \
   PCW_P2F_QSPI_INTR {0} \
   PCW_P2F_SDIO0_INTR {0} \
   PCW_P2F_SDIO1_INTR {0} \
   PCW_P2F_SMC_INTR {0} \
   PCW_P2F_SPI0_INTR {0} \
   PCW_P2F_SPI1_INTR {0} \
   PCW_P2F_UART0_INTR {0} \
   PCW_P2F_UART1_INTR {0} \
   PCW_P2F_USB0_INTR {0} \
   PCW_P2F_USB1_INTR {0} \
   PCW_PACKAGE_DDR_BOARD_DELAY0 {0.223} \
   PCW_PACKAGE_DDR_BOARD_DELAY1 {0.212} \
   PCW_PACKAGE_DDR_BOARD_DELAY2 {0.085} \
   PCW_PACKAGE_DDR_BOARD_DELAY3 {0.092} \
   PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_0 {0.040} \
   PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_1 {0.058} \
   PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_2 {-0.009} \
   PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_3 {-0.033} \
   PCW_PACKAGE_NAME {clg400} \
   PCW_PCAP_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_PCAP_PERIPHERAL_DIVISOR0 {5} \
   PCW_PCAP_PERIPHERAL_FREQMHZ {200} \
   PCW_PERIPHERAL_BOARD_PRESET {None} \
   PCW_PJTAG_PERIPHERAL_ENABLE {0} \
   PCW_PJTAG_PJTAG_IO {<Select>} \
   PCW_PLL_BYPASSMODE_ENABLE {0} \
   PCW_PRESET_BANK0_VOLTAGE {LVCMOS 3.3V} \
   PCW_PRESET_BANK1_VOLTAGE {LVCMOS 1.8V} \
   PCW_PS7_SI_REV {PRODUCTION} \
   PCW_QSPI_GRP_FBCLK_ENABLE {0} \
   PCW_QSPI_GRP_FBCLK_IO {<Select>} \
   PCW_QSPI_GRP_IO1_ENABLE {0} \
   PCW_QSPI_GRP_IO1_IO {<Select>} \
   PCW_QSPI_GRP_SINGLE_SS_ENABLE {0} \
   PCW_QSPI_GRP_SINGLE_SS_IO {<Select>} \
   PCW_QSPI_GRP_SS1_ENABLE {0} \
   PCW_QSPI_GRP_SS1_IO {<Select>} \
   PCW_QSPI_INTERNAL_HIGHADDRESS {0xFCFFFFFF} \
   PCW_QSPI_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_QSPI_PERIPHERAL_DIVISOR0 {1} \
   PCW_QSPI_PERIPHERAL_ENABLE {0} \
   PCW_QSPI_PERIPHERAL_FREQMHZ {200} \
   PCW_QSPI_QSPI_IO {<Select>} \
   PCW_SD0_GRP_CD_ENABLE {1} \
   PCW_SD0_GRP_CD_IO {MIO 47} \
   PCW_SD0_GRP_POW_ENABLE {0} \
   PCW_SD0_GRP_POW_IO {<Select>} \
   PCW_SD0_GRP_WP_ENABLE {0} \
   PCW_SD0_GRP_WP_IO {<Select>} \
   PCW_SD0_PERIPHERAL_ENABLE {1} \
   PCW_SD0_SD0_IO {MIO 40 .. 45} \
   PCW_SD1_GRP_CD_ENABLE {0} \
   PCW_SD1_GRP_CD_IO {<Select>} \
   PCW_SD1_GRP_POW_ENABLE {0} \
   PCW_SD1_GRP_POW_IO {<Select>} \
   PCW_SD1_GRP_WP_ENABLE {0} \
   PCW_SD1_GRP_WP_IO {<Select>} \
   PCW_SD1_PERIPHERAL_ENABLE {0} \
   PCW_SD1_SD1_IO {<Select>} \
   PCW_SDIO0_BASEADDR {0xE0100000} \
   PCW_SDIO0_HIGHADDR {0xE0100FFF} \
   PCW_SDIO1_BASEADDR {0xE0101000} \
   PCW_SDIO1_HIGHADDR {0xE0101FFF} \
   PCW_SDIO_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_SDIO_PERIPHERAL_DIVISOR0 {20} \
   PCW_SDIO_PERIPHERAL_FREQMHZ {50} \
   PCW_SDIO_PERIPHERAL_VALID {1} \
   PCW_SINGLE_QSPI_DATA_MODE {<Select>} \
   PCW_SMC_CYCLE_T0 {NA} \
   PCW_SMC_CYCLE_T1 {NA} \
   PCW_SMC_CYCLE_T2 {NA} \
   PCW_SMC_CYCLE_T3 {NA} \
   PCW_SMC_CYCLE_T4 {NA} \
   PCW_SMC_CYCLE_T5 {NA} \
   PCW_SMC_CYCLE_T6 {NA} \
   PCW_SMC_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_SMC_PERIPHERAL_DIVISOR0 {1} \
   PCW_SMC_PERIPHERAL_FREQMHZ {100} \
   PCW_SMC_PERIPHERAL_VALID {0} \
   PCW_SPI_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_SPI_PERIPHERAL_DIVISOR0 {6} \
   PCW_SPI_PERIPHERAL_FREQMHZ {166.666666} \
   PCW_SPI_PERIPHERAL_VALID {1} \
   PCW_S_AXI_ACP_ARUSER_VAL {31} \
   PCW_S_AXI_ACP_AWUSER_VAL {31} \
   PCW_S_AXI_ACP_ID_WIDTH {3} \
   PCW_S_AXI_GP0_ID_WIDTH {6} \
   PCW_S_AXI_GP1_ID_WIDTH {6} \
   PCW_S_AXI_HP0_DATA_WIDTH {64} \
   PCW_S_AXI_HP0_ID_WIDTH {6} \
   PCW_S_AXI_HP1_DATA_WIDTH {64} \
   PCW_S_AXI_HP1_ID_WIDTH {6} \
   PCW_S_AXI_HP2_DATA_WIDTH {64} \
   PCW_S_AXI_HP2_ID_WIDTH {6} \
   PCW_S_AXI_HP3_DATA_WIDTH {64} \
   PCW_S_AXI_HP3_ID_WIDTH {6} \
   PCW_TPIU_PERIPHERAL_CLKSRC {External} \
   PCW_TPIU_PERIPHERAL_DIVISOR0 {1} \
   PCW_TPIU_PERIPHERAL_FREQMHZ {200} \
   PCW_TRACE_BUFFER_CLOCK_DELAY {12} \
   PCW_TRACE_BUFFER_FIFO_SIZE {128} \
   PCW_TRACE_GRP_16BIT_ENABLE {0} \
   PCW_TRACE_GRP_16BIT_IO {<Select>} \
   PCW_TRACE_GRP_2BIT_ENABLE {0} \
   PCW_TRACE_GRP_2BIT_IO {<Select>} \
   PCW_TRACE_GRP_32BIT_ENABLE {0} \
   PCW_TRACE_GRP_32BIT_IO {<Select>} \
   PCW_TRACE_GRP_4BIT_ENABLE {0} \
   PCW_TRACE_GRP_4BIT_IO {<Select>} \
   PCW_TRACE_GRP_8BIT_ENABLE {0} \
   PCW_TRACE_GRP_8BIT_IO {<Select>} \
   PCW_TRACE_INTERNAL_WIDTH {2} \
   PCW_TRACE_PERIPHERAL_ENABLE {0} \
   PCW_TRACE_PIPELINE_WIDTH {8} \
   PCW_TRACE_TRACE_IO {<Select>} \
   PCW_TTC0_BASEADDR {0xE0104000} \
   PCW_TTC0_CLK0_PERIPHERAL_CLKSRC {CPU_1X} \
   PCW_TTC0_CLK0_PERIPHERAL_DIVISOR0 {1} \
   PCW_TTC0_CLK0_PERIPHERAL_FREQMHZ {133.333333} \
   PCW_TTC0_CLK1_PERIPHERAL_CLKSRC {CPU_1X} \
   PCW_TTC0_CLK1_PERIPHERAL_DIVISOR0 {1} \
   PCW_TTC0_CLK1_PERIPHERAL_FREQMHZ {133.333333} \
   PCW_TTC0_CLK2_PERIPHERAL_CLKSRC {CPU_1X} \
   PCW_TTC0_CLK2_PERIPHERAL_DIVISOR0 {1} \
   PCW_TTC0_CLK2_PERIPHERAL_FREQMHZ {133.333333} \
   PCW_TTC0_HIGHADDR {0xE0104fff} \
   PCW_TTC0_PERIPHERAL_ENABLE {0} \
   PCW_TTC0_TTC0_IO {<Select>} \
   PCW_TTC1_BASEADDR {0xE0105000} \
   PCW_TTC1_CLK0_PERIPHERAL_CLKSRC {CPU_1X} \
   PCW_TTC1_CLK0_PERIPHERAL_DIVISOR0 {1} \
   PCW_TTC1_CLK0_PERIPHERAL_FREQMHZ {133.333333} \
   PCW_TTC1_CLK1_PERIPHERAL_CLKSRC {CPU_1X} \
   PCW_TTC1_CLK1_PERIPHERAL_DIVISOR0 {1} \
   PCW_TTC1_CLK1_PERIPHERAL_FREQMHZ {133.333333} \
   PCW_TTC1_CLK2_PERIPHERAL_CLKSRC {CPU_1X} \
   PCW_TTC1_CLK2_PERIPHERAL_DIVISOR0 {1} \
   PCW_TTC1_CLK2_PERIPHERAL_FREQMHZ {133.333333} \
   PCW_TTC1_HIGHADDR {0xE0105fff} \
   PCW_TTC1_PERIPHERAL_ENABLE {0} \
   PCW_TTC1_TTC1_IO {<Select>} \
   PCW_TTC_PERIPHERAL_FREQMHZ {50} \
   PCW_UART0_BASEADDR {0xE0000000} \
   PCW_UART0_BAUD_RATE {921600} \
   PCW_UART0_GRP_FULL_ENABLE {0} \
   PCW_UART0_GRP_FULL_IO {<Select>} \
   PCW_UART0_HIGHADDR {0xE0000FFF} \
   PCW_UART0_PERIPHERAL_ENABLE {1} \
   PCW_UART0_UART0_IO {MIO 14 .. 15} \
   PCW_UART1_BASEADDR {0xE0001000} \
   PCW_UART1_BAUD_RATE {115200} \
   PCW_UART1_GRP_FULL_ENABLE {0} \
   PCW_UART1_GRP_FULL_IO {<Select>} \
   PCW_UART1_HIGHADDR {0xE0001FFF} \
   PCW_UART1_PERIPHERAL_ENABLE {0} \
   PCW_UART1_UART1_IO {<Select>} \
   PCW_UART_PERIPHERAL_CLKSRC {IO PLL} \
   PCW_UART_PERIPHERAL_DIVISOR0 {10} \
   PCW_UART_PERIPHERAL_FREQMHZ {100} \
   PCW_UART_PERIPHERAL_VALID {1} \
   PCW_UIPARAM_ACT_DDR_FREQ_MHZ {525.000000} \
   PCW_UIPARAM_DDR_ADV_ENABLE {0} \
   PCW_UIPARAM_DDR_AL {0} \
   PCW_UIPARAM_DDR_BANK_ADDR_COUNT {3} \
   PCW_UIPARAM_DDR_BL {8} \
   PCW_UIPARAM_DDR_BOARD_DELAY0 {0.223} \
   PCW_UIPARAM_DDR_BOARD_DELAY1 {0.212} \
   PCW_UIPARAM_DDR_BOARD_DELAY2 {0.085} \
   PCW_UIPARAM_DDR_BOARD_DELAY3 {0.092} \
   PCW_UIPARAM_DDR_BUS_WIDTH {16 Bit} \
   PCW_UIPARAM_DDR_CL {7} \
   PCW_UIPARAM_DDR_CLOCK_0_LENGTH_MM {25.8} \
   PCW_UIPARAM_DDR_CLOCK_0_PACKAGE_LENGTH {80.4535} \
   PCW_UIPARAM_DDR_CLOCK_0_PROPOGATION_DELAY {160} \
   PCW_UIPARAM_DDR_CLOCK_1_LENGTH_MM {25.8} \
   PCW_UIPARAM_DDR_CLOCK_1_PACKAGE_LENGTH {80.4535} \
   PCW_UIPARAM_DDR_CLOCK_1_PROPOGATION_DELAY {160} \
   PCW_UIPARAM_DDR_CLOCK_2_LENGTH_MM {0} \
   PCW_UIPARAM_DDR_CLOCK_2_PACKAGE_LENGTH {80.4535} \
   PCW_UIPARAM_DDR_CLOCK_2_PROPOGATION_DELAY {160} \
   PCW_UIPARAM_DDR_CLOCK_3_LENGTH_MM {0} \
   PCW_UIPARAM_DDR_CLOCK_3_PACKAGE_LENGTH {80.4535} \
   PCW_UIPARAM_DDR_CLOCK_3_PROPOGATION_DELAY {160} \
   PCW_UIPARAM_DDR_CLOCK_STOP_EN {0} \
   PCW_UIPARAM_DDR_COL_ADDR_COUNT {10} \
   PCW_UIPARAM_DDR_CWL {6} \
   PCW_UIPARAM_DDR_DEVICE_CAPACITY {4096 MBits} \
   PCW_UIPARAM_DDR_DQS_0_LENGTH_MM {15.6} \
   PCW_UIPARAM_DDR_DQS_0_PACKAGE_LENGTH {105.056} \
   PCW_UIPARAM_DDR_DQS_0_PROPOGATION_DELAY {160} \
   PCW_UIPARAM_DDR_DQS_1_LENGTH_MM {18.8} \
   PCW_UIPARAM_DDR_DQS_1_PACKAGE_LENGTH {66.904} \
   PCW_UIPARAM_DDR_DQS_1_PROPOGATION_DELAY {160} \
   PCW_UIPARAM_DDR_DQS_2_LENGTH_MM {0} \
   PCW_UIPARAM_DDR_DQS_2_PACKAGE_LENGTH {89.1715} \
   PCW_UIPARAM_DDR_DQS_2_PROPOGATION_DELAY {160} \
   PCW_UIPARAM_DDR_DQS_3_LENGTH_MM {0} \
   PCW_UIPARAM_DDR_DQS_3_PACKAGE_LENGTH {113.63} \
   PCW_UIPARAM_DDR_DQS_3_PROPOGATION_DELAY {160} \
   PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 {0.040} \
   PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 {0.058} \
   PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2 {-0.009} \
   PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3 {-0.033} \
   PCW_UIPARAM_DDR_DQ_0_LENGTH_MM {16.5} \
   PCW_UIPARAM_DDR_DQ_0_PACKAGE_LENGTH {98.503} \
   PCW_UIPARAM_DDR_DQ_0_PROPOGATION_DELAY {160} \
   PCW_UIPARAM_DDR_DQ_1_LENGTH_MM {18} \
   PCW_UIPARAM_DDR_DQ_1_PACKAGE_LENGTH {68.5855} \
   PCW_UIPARAM_DDR_DQ_1_PROPOGATION_DELAY {160} \
   PCW_UIPARAM_DDR_DQ_2_LENGTH_MM {0} \
   PCW_UIPARAM_DDR_DQ_2_PACKAGE_LENGTH {90.295} \
   PCW_UIPARAM_DDR_DQ_2_PROPOGATION_DELAY {160} \
   PCW_UIPARAM_DDR_DQ_3_LENGTH_MM {0} \
   PCW_UIPARAM_DDR_DQ_3_PACKAGE_LENGTH {103.977} \
   PCW_UIPARAM_DDR_DQ_3_PROPOGATION_DELAY {160} \
   PCW_UIPARAM_DDR_DRAM_WIDTH {16 Bits} \
   PCW_UIPARAM_DDR_ECC {Disabled} \
   PCW_UIPARAM_DDR_ENABLE {1} \
   PCW_UIPARAM_DDR_FREQ_MHZ {525} \
   PCW_UIPARAM_DDR_HIGH_TEMP {Normal (0-85)} \
   PCW_UIPARAM_DDR_MEMORY_TYPE {DDR 3} \
   PCW_UIPARAM_DDR_PARTNO {MT41K256M16 RE-125} \
   PCW_UIPARAM_DDR_ROW_ADDR_COUNT {15} \
   PCW_UIPARAM_DDR_SPEED_BIN {DDR3_1066F} \
   PCW_UIPARAM_DDR_TRAIN_DATA_EYE {1} \
   PCW_UIPARAM_DDR_TRAIN_READ_GATE {1} \
   PCW_UIPARAM_DDR_TRAIN_WRITE_LEVEL {1} \
   PCW_UIPARAM_DDR_T_FAW {40.0} \
   PCW_UIPARAM_DDR_T_RAS_MIN {35.0} \
   PCW_UIPARAM_DDR_T_RC {48.75} \
   PCW_UIPARAM_DDR_T_RCD {7} \
   PCW_UIPARAM_DDR_T_RP {7} \
   PCW_UIPARAM_DDR_USE_INTERNAL_VREF {0} \
   PCW_UIPARAM_GENERATE_SUMMARY {NA} \
   PCW_USB0_BASEADDR {0xE0102000} \
   PCW_USB0_HIGHADDR {0xE0102fff} \
   PCW_USB0_PERIPHERAL_ENABLE {1} \
   PCW_USB0_PERIPHERAL_FREQMHZ {60} \
   PCW_USB0_RESET_ENABLE {1} \
   PCW_USB0_RESET_IO {MIO 46} \
   PCW_USB0_USB0_IO {MIO 28 .. 39} \
   PCW_USB1_BASEADDR {0xE0103000} \
   PCW_USB1_HIGHADDR {0xE0103fff} \
   PCW_USB1_PERIPHERAL_ENABLE {0} \
   PCW_USB1_PERIPHERAL_FREQMHZ {60} \
   PCW_USB1_RESET_ENABLE {0} \
   PCW_USB1_RESET_IO {<Select>} \
   PCW_USB1_USB1_IO {<Select>} \
   PCW_USB_RESET_ENABLE {1} \
   PCW_USB_RESET_POLARITY {Active Low} \
   PCW_USB_RESET_SELECT {Share reset pin} \
   PCW_USE_AXI_FABRIC_IDLE {0} \
   PCW_USE_AXI_NONSECURE {0} \
   PCW_USE_CORESIGHT {0} \
   PCW_USE_CROSS_TRIGGER {0} \
   PCW_USE_CR_FABRIC {1} \
   PCW_USE_DDR_BYPASS {0} \
   PCW_USE_DEBUG {0} \
   PCW_USE_DEFAULT_ACP_USER_VAL {0} \
   PCW_USE_DMA0 {0} \
   PCW_USE_DMA1 {0} \
   PCW_USE_DMA2 {0} \
   PCW_USE_DMA3 {0} \
   PCW_USE_EXPANDED_IOP {0} \
   PCW_USE_EXPANDED_PS_SLCR_REGISTERS {0} \
   PCW_USE_FABRIC_INTERRUPT {1} \
   PCW_USE_HIGH_OCM {0} \
   PCW_USE_M_AXI_GP0 {1} \
   PCW_USE_M_AXI_GP1 {0} \
   PCW_USE_PROC_EVENT_BUS {0} \
   PCW_USE_PS_SLCR_REGISTERS {0} \
   PCW_USE_S_AXI_ACP {0} \
   PCW_USE_S_AXI_GP0 {0} \
   PCW_USE_S_AXI_GP1 {0} \
   PCW_USE_S_AXI_HP0 {1} \
   PCW_USE_S_AXI_HP1 {0} \
   PCW_USE_S_AXI_HP2 {0} \
   PCW_USE_S_AXI_HP3 {0} \
   PCW_USE_TRACE {0} \
   PCW_USE_TRACE_DATA_EDGE_DETECTOR {0} \
   PCW_VALUE_SILVERSION {3} \
   PCW_WDT_PERIPHERAL_CLKSRC {CPU_1X} \
   PCW_WDT_PERIPHERAL_DIVISOR0 {1} \
   PCW_WDT_PERIPHERAL_ENABLE {0} \
   PCW_WDT_PERIPHERAL_FREQMHZ {133.333333} \
   PCW_WDT_WDT_IO {<Select>} \
 ] 

ad_ip_instance xlconcat sys_concat_intc
ad_ip_parameter sys_concat_intc CONFIG.NUM_PORTS 16

ad_ip_instance proc_sys_reset sys_rstgen
ad_ip_parameter sys_rstgen CONFIG.C_EXT_RST_WIDTH 1
ad_ip_instance proc_sys_reset sys_200m_rstgen
ad_ip_parameter sys_200m_rstgen CONFIG.C_EXT_RST_WIDTH 1


# system reset/clock definitions

ad_connect  sys_cpu_clk sys_ps7/FCLK_CLK0
ad_connect  sys_200m_clk sys_ps7/FCLK_CLK1
ad_connect  sys_cpu_reset sys_rstgen/peripheral_reset
ad_connect  sys_cpu_resetn sys_rstgen/peripheral_aresetn
ad_connect  sys_cpu_clk sys_rstgen/slowest_sync_clk
ad_connect  sys_rstgen/ext_reset_in sys_ps7/FCLK_RESET0_N
ad_connect  sys_200m_reset sys_200m_rstgen/peripheral_reset
ad_connect  sys_200m_resetn sys_200m_rstgen/peripheral_aresetn
ad_connect  sys_200m_clk sys_200m_rstgen/slowest_sync_clk
ad_connect  sys_200m_rstgen/ext_reset_in sys_ps7/FCLK_RESET1_N

# generic system clocks pointers

set sys_cpu_clk           [get_bd_nets sys_cpu_clk]
set sys_dma_clk           [get_bd_nets sys_200m_clk]
set sys_iodelay_clk       [get_bd_nets sys_200m_clk]

set sys_cpu_reset         [get_bd_nets sys_cpu_reset]
set sys_cpu_resetn        [get_bd_nets sys_cpu_resetn]
set sys_dma_reset         [get_bd_nets sys_200m_reset]
set sys_dma_resetn        [get_bd_nets sys_200m_resetn]
set sys_iodelay_reset     [get_bd_nets sys_200m_reset]
set sys_iodelay_resetn    [get_bd_nets sys_200m_resetn]

# interface connections

ad_connect  ddr           sys_ps7/DDR
ad_connect  gpio_i        sys_ps7/GPIO_I
ad_connect  gpio_o        sys_ps7/GPIO_O
ad_connect  gpio_t        sys_ps7/GPIO_T
ad_connect  fixed_io      sys_ps7/FIXED_IO


# spi connections

# ad_connect  spi0_csn_2_o sys_ps7/SPI0_SS2_O
# ad_connect  spi0_csn_1_o sys_ps7/SPI0_SS1_O
# ad_connect  spi0_csn_0_o sys_ps7/SPI0_SS_O
# ad_connect  spi0_csn_i sys_ps7/SPI0_SS_I
# ad_connect  spi0_clk_i sys_ps7/SPI0_SCLK_I
# ad_connect  spi0_clk_o sys_ps7/SPI0_SCLK_O
# ad_connect  spi0_sdo_i sys_ps7/SPI0_MOSI_I
# ad_connect  spi0_sdo_o sys_ps7/SPI0_MOSI_O
# ad_connect  spi0_sdi_i sys_ps7/SPI0_MISO_I

# ad_connect  spi1_csn_2_o sys_ps7/SPI1_SS2_O
# ad_connect  spi1_csn_1_o sys_ps7/SPI1_SS1_O
# ad_connect  spi1_csn_0_o sys_ps7/SPI1_SS_O
# ad_connect  spi1_csn_i sys_ps7/SPI1_SS_I
# ad_connect  spi1_clk_i sys_ps7/SPI1_SCLK_I
# ad_connect  spi1_clk_o sys_ps7/SPI1_SCLK_O
# ad_connect  spi1_sdo_i sys_ps7/SPI1_MOSI_I
# ad_connect  spi1_sdo_o sys_ps7/SPI1_MOSI_O
# ad_connect  spi1_sdi_i sys_ps7/SPI1_MISO_I

# system id

ad_ip_instance axi_sysid axi_sysid_0
ad_ip_instance sysid_rom rom_sys_0

ad_connect  axi_sysid_0/rom_addr   	rom_sys_0/rom_addr
ad_connect  axi_sysid_0/sys_rom_data   	rom_sys_0/rom_data
ad_connect  sys_cpu_clk                 rom_sys_0/clk

# interrupts

ad_connect  sys_concat_intc/dout  sys_ps7/IRQ_F2P
ad_connect  sys_concat_intc/In15  GND
ad_connect  sys_concat_intc/In14  GND
ad_connect  sys_concat_intc/In13  GND
ad_connect  sys_concat_intc/In12  GND
ad_connect  sys_concat_intc/In11  GND
ad_connect  sys_concat_intc/In10  GND
ad_connect  sys_concat_intc/In9   GND
ad_connect  sys_concat_intc/In8   GND
ad_connect  sys_concat_intc/In7   GND
ad_connect  sys_concat_intc/In6   GND
ad_connect  sys_concat_intc/In5   GND
ad_connect  sys_concat_intc/In4   GND
ad_connect  sys_concat_intc/In3   GND
ad_connect  sys_concat_intc/In2   GND
ad_connect  sys_concat_intc/In1   GND
ad_connect  sys_concat_intc/In0   GND

# interconnects and address mapping

ad_cpu_interconnect 0x45000000 axi_sysid_0
