ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_APU_PERIPHERAL_FREQMHZ {650.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_CAN0_PERIPHERAL_FREQMHZ {23.8095} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_CAN1_PERIPHERAL_FREQMHZ {23.8095} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_CAN_PERIPHERAL_FREQMHZ {10.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_DCI_PERIPHERAL_FREQMHZ {10.096154} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_ENET0_PERIPHERAL_FREQMHZ {125.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_ENET1_PERIPHERAL_FREQMHZ {10.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_FPGA0_PERIPHERAL_FREQMHZ {100.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_FPGA1_PERIPHERAL_FREQMHZ {10.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_FPGA2_PERIPHERAL_FREQMHZ {10.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_FPGA3_PERIPHERAL_FREQMHZ {10.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_I2C_PERIPHERAL_FREQMHZ {50} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_PCAP_PERIPHERAL_FREQMHZ {200.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_QSPI_PERIPHERAL_FREQMHZ {10.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_SDIO_PERIPHERAL_FREQMHZ {50.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_SMC_PERIPHERAL_FREQMHZ {10.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_SPI_PERIPHERAL_FREQMHZ {166.666672} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_TPIU_PERIPHERAL_FREQMHZ {200.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_TTC0_CLK0_PERIPHERAL_FREQMHZ {108.333336} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_TTC0_CLK1_PERIPHERAL_FREQMHZ {108.333336} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_TTC0_CLK2_PERIPHERAL_FREQMHZ {108.333336} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_TTC1_CLK0_PERIPHERAL_FREQMHZ {108.333336} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_TTC1_CLK1_PERIPHERAL_FREQMHZ {108.333336} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_TTC1_CLK2_PERIPHERAL_FREQMHZ {108.333336} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_TTC_PERIPHERAL_FREQMHZ {50} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_UART_PERIPHERAL_FREQMHZ {100.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_USB0_PERIPHERAL_FREQMHZ {60} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_USB1_PERIPHERAL_FREQMHZ {60} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ACT_WDT_PERIPHERAL_FREQMHZ {108.333336} 
ad_ip_parameter sys_ps7 CONFIG.PCW_APU_CLK_RATIO_ENABLE {6:2:1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_APU_PERIPHERAL_FREQMHZ {650} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ARMPLL_CTRL_FBDIV {26} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN0_BASEADDR {0xE0008000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN0_CAN0_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN0_GRP_CLK_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN0_GRP_CLK_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN0_HIGHADDR {0xE0008FFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN0_PERIPHERAL_CLKSRC {External} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN0_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN0_PERIPHERAL_FREQMHZ {-1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN1_BASEADDR {0xE0009000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN1_CAN1_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN1_GRP_CLK_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN1_GRP_CLK_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN1_HIGHADDR {0xE0009FFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN1_PERIPHERAL_CLKSRC {External} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN1_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN1_PERIPHERAL_FREQMHZ {-1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN_PERIPHERAL_DIVISOR1 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN_PERIPHERAL_FREQMHZ {100} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CAN_PERIPHERAL_VALID {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CLK0_FREQ {100000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CLK1_FREQ {10000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CLK2_FREQ {10000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CLK3_FREQ {10000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CORE0_FIQ_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CORE0_IRQ_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CORE1_FIQ_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CORE1_IRQ_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CPU_CPU_6X4X_MAX_RANGE {667} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CPU_CPU_PLL_FREQMHZ {1300.000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CPU_PERIPHERAL_CLKSRC {ARM PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CPU_PERIPHERAL_DIVISOR0 {2} 
ad_ip_parameter sys_ps7 CONFIG.PCW_CRYSTAL_PERIPHERAL_FREQMHZ {50} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DCI_PERIPHERAL_CLKSRC {DDR PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DCI_PERIPHERAL_DIVISOR0 {52} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DCI_PERIPHERAL_DIVISOR1 {2} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DCI_PERIPHERAL_FREQMHZ {10.159} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDRPLL_CTRL_FBDIV {21} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_DDR_PLL_FREQMHZ {1050.000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_HPRLPR_QUEUE_PARTITION {HPR(0)/LPR(32)} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_HPR_TO_CRITICAL_PRIORITY_LEVEL {15} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_LPR_TO_CRITICAL_PRIORITY_LEVEL {2} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PERIPHERAL_CLKSRC {DDR PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PERIPHERAL_DIVISOR0 {2} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PORT0_HPR_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PORT1_HPR_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PORT2_HPR_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PORT3_HPR_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PRIORITY_READPORT_0 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PRIORITY_READPORT_1 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PRIORITY_READPORT_2 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PRIORITY_READPORT_3 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PRIORITY_WRITEPORT_0 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PRIORITY_WRITEPORT_1 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PRIORITY_WRITEPORT_2 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_PRIORITY_WRITEPORT_3 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_RAM_BASEADDR {0x00100000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_RAM_HIGHADDR {0x1FFFFFFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DDR_WRITE_TO_CRITICAL_PRIORITY_LEVEL {2} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DM_WIDTH {4} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DQS_WIDTH {4} 
ad_ip_parameter sys_ps7 CONFIG.PCW_DQ_WIDTH {32} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET0_BASEADDR {0xE000B000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET0_ENET0_IO {MIO 16 .. 27} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET0_GRP_MDIO_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET0_GRP_MDIO_IO {MIO 52 .. 53} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET0_HIGHADDR {0xE000BFFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET0_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET0_PERIPHERAL_DIVISOR0 {8} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET0_PERIPHERAL_DIVISOR1 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET0_PERIPHERAL_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET0_PERIPHERAL_FREQMHZ {1000 Mbps} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET0_RESET_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET0_RESET_IO {MIO 9} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET1_BASEADDR {0xE000C000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET1_ENET1_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET1_GRP_MDIO_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET1_GRP_MDIO_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET1_HIGHADDR {0xE000CFFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET1_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET1_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET1_PERIPHERAL_DIVISOR1 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET1_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET1_PERIPHERAL_FREQMHZ {1000 Mbps} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET1_RESET_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET1_RESET_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET_RESET_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET_RESET_POLARITY {Active Low} 
ad_ip_parameter sys_ps7 CONFIG.PCW_ENET_RESET_SELECT {Share reset pin} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_4K_TIMER {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_CAN0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_CAN1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_CLK0_PORT {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_CLK1_PORT {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_CLK2_PORT {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_CLK3_PORT {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_CLKTRIG0_PORT {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_CLKTRIG1_PORT {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_CLKTRIG2_PORT {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_CLKTRIG3_PORT {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_DDR {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_CAN0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_CAN1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_CD_SDIO0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_CD_SDIO1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_ENET0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_ENET1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_GPIO {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_I2C0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_I2C1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_MODEM_UART0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_MODEM_UART1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_PJTAG {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_SDIO0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_SDIO1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_SPI0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_SPI1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_SRAM_INT {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_TRACE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_TTC0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_TTC1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_UART0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_UART1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_WDT {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_WP_SDIO0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_EMIO_WP_SDIO1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_ENET0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_ENET1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_GPIO {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_I2C0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_I2C1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_MODEM_UART0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_MODEM_UART1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_PJTAG {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_PTP_ENET0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_PTP_ENET1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_QSPI {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_RST0_PORT {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_RST1_PORT {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_RST2_PORT {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_RST3_PORT {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_SDIO0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_SDIO1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_SMC {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_SPI0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_SPI1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_TRACE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_TTC0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_TTC1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_UART0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_UART1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_USB0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_USB1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_EN_WDT {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK0_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK0_PERIPHERAL_DIVISOR0 {5} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK0_PERIPHERAL_DIVISOR1 {2} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK1_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK1_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK1_PERIPHERAL_DIVISOR1 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK2_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK2_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK2_PERIPHERAL_DIVISOR1 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK3_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK3_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK3_PERIPHERAL_DIVISOR1 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK_CLK0_BUF {TRUE} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK_CLK1_BUF {FALSE} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK_CLK2_BUF {FALSE} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FCLK_CLK3_BUF {FALSE} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {100} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FPGA1_PERIPHERAL_FREQMHZ {200} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FPGA2_PERIPHERAL_FREQMHZ {120} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FPGA3_PERIPHERAL_FREQMHZ {50} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FPGA_FCLK0_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FPGA_FCLK1_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FPGA_FCLK2_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FPGA_FCLK3_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FTM_CTI_IN0 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FTM_CTI_IN1 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FTM_CTI_IN2 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FTM_CTI_IN3 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FTM_CTI_OUT0 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FTM_CTI_OUT1 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FTM_CTI_OUT2 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_FTM_CTI_OUT3 {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GP0_EN_MODIFIABLE_TXN {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GP0_NUM_READ_THREADS {4} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GP0_NUM_WRITE_THREADS {4} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GP1_EN_MODIFIABLE_TXN {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GP1_NUM_READ_THREADS {4} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GP1_NUM_WRITE_THREADS {4} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GPIO_BASEADDR {0xE000A000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GPIO_EMIO_GPIO_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GPIO_EMIO_GPIO_IO {64} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GPIO_EMIO_GPIO_WIDTH {64} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GPIO_HIGHADDR {0xE000AFFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GPIO_MIO_GPIO_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GPIO_MIO_GPIO_IO {MIO} 
ad_ip_parameter sys_ps7 CONFIG.PCW_GPIO_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C0_BASEADDR {0xE0004000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C0_GRP_INT_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C0_GRP_INT_IO {EMIO} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C0_HIGHADDR {0xE0004FFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C0_I2C0_IO {EMIO} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C0_PERIPHERAL_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C0_RESET_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C0_RESET_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C1_BASEADDR {0xE0005000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C1_GRP_INT_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C1_GRP_INT_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C1_HIGHADDR {0xE0005FFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C1_I2C1_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C1_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C1_RESET_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C1_RESET_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C_PERIPHERAL_FREQMHZ {108.333336} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C_RESET_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C_RESET_POLARITY {Active Low} 
ad_ip_parameter sys_ps7 CONFIG.PCW_I2C_RESET_SELECT {Share reset pin} 
ad_ip_parameter sys_ps7 CONFIG.PCW_IMPORT_BOARD_PRESET {None} 
ad_ip_parameter sys_ps7 CONFIG.PCW_INCLUDE_ACP_TRANS_CHECK {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_INCLUDE_TRACE_BUFFER {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_IOPLL_CTRL_FBDIV {20} 
ad_ip_parameter sys_ps7 CONFIG.PCW_IO_IO_PLL_FREQMHZ {1000.000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_IRQ_F2P_INTR {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_IRQ_F2P_MODE {REVERSE} 
ad_ip_parameter sys_ps7 CONFIG.PCW_M_AXI_GP0_ENABLE_STATIC_REMAP {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_M_AXI_GP0_ID_WIDTH {12} 
ad_ip_parameter sys_ps7 CONFIG.PCW_M_AXI_GP0_SUPPORT_NARROW_BURST {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_M_AXI_GP0_THREAD_ID_WIDTH {12} 
ad_ip_parameter sys_ps7 CONFIG.PCW_M_AXI_GP1_ENABLE_STATIC_REMAP {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_M_AXI_GP1_ID_WIDTH {12} 
ad_ip_parameter sys_ps7 CONFIG.PCW_M_AXI_GP1_SUPPORT_NARROW_BURST {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_M_AXI_GP1_THREAD_ID_WIDTH {12} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NAND_CYCLES_T_AR {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NAND_CYCLES_T_CLR {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NAND_CYCLES_T_RC {11} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NAND_CYCLES_T_REA {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NAND_CYCLES_T_RR {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NAND_CYCLES_T_WC {11} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NAND_CYCLES_T_WP {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NAND_GRP_D8_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NAND_GRP_D8_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NAND_NAND_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NAND_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS0_T_CEOE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS0_T_PC {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS0_T_RC {11} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS0_T_TR {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS0_T_WC {11} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS0_T_WP {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS0_WE_TIME {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS1_T_CEOE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS1_T_PC {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS1_T_RC {11} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS1_T_TR {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS1_T_WC {11} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS1_T_WP {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_CS1_WE_TIME {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_GRP_A25_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_GRP_A25_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_GRP_CS0_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_GRP_CS0_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_GRP_CS1_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_GRP_CS1_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_GRP_SRAM_CS0_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_GRP_SRAM_CS0_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_GRP_SRAM_CS1_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_GRP_SRAM_CS1_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_GRP_SRAM_INT_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_GRP_SRAM_INT_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_NOR_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS0_T_CEOE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS0_T_PC {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS0_T_RC {11} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS0_T_TR {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS0_T_WC {11} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS0_T_WP {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS0_WE_TIME {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS1_T_CEOE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS1_T_PC {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS1_T_RC {11} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS1_T_TR {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS1_T_WC {11} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS1_T_WP {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_NOR_SRAM_CS1_WE_TIME {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_OVERRIDE_BASIC_CLOCK {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_CAN0_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_CAN1_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_CTI_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_DMAC0_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_DMAC1_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_DMAC2_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_DMAC3_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_DMAC4_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_DMAC5_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_DMAC6_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_DMAC7_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_DMAC_ABORT_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_ENET0_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_ENET1_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_GPIO_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_I2C0_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_I2C1_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_QSPI_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_SDIO0_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_SDIO1_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_SMC_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_SPI0_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_SPI1_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_UART0_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_UART1_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_USB0_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_P2F_USB1_INTR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY0 {0.223} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY1 {0.212} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY2 {0.085} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY3 {0.092} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_0 {0.040} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_1 {0.058} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_2 {-0.009} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_3 {-0.033} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PACKAGE_NAME {clg400} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PCAP_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PCAP_PERIPHERAL_DIVISOR0 {5} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PCAP_PERIPHERAL_FREQMHZ {200} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PERIPHERAL_BOARD_PRESET {None} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PJTAG_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PJTAG_PJTAG_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PLL_BYPASSMODE_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PRESET_BANK0_VOLTAGE {LVCMOS 3.3V} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PRESET_BANK1_VOLTAGE {LVCMOS 1.8V} 
ad_ip_parameter sys_ps7 CONFIG.PCW_PS7_SI_REV {PRODUCTION} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_GRP_FBCLK_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_GRP_FBCLK_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_GRP_IO1_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_GRP_IO1_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_GRP_SINGLE_SS_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_GRP_SINGLE_SS_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_GRP_SS1_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_GRP_SS1_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_INTERNAL_HIGHADDRESS {0xFCFFFFFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_PERIPHERAL_FREQMHZ {200} 
ad_ip_parameter sys_ps7 CONFIG.PCW_QSPI_QSPI_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD0_GRP_CD_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD0_GRP_CD_IO {MIO 47} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD0_GRP_POW_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD0_GRP_POW_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD0_GRP_WP_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD0_GRP_WP_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD0_PERIPHERAL_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD0_SD0_IO {MIO 40 .. 45} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD1_GRP_CD_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD1_GRP_CD_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD1_GRP_POW_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD1_GRP_POW_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD1_GRP_WP_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD1_GRP_WP_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD1_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SD1_SD1_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SDIO0_BASEADDR {0xE0100000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SDIO0_HIGHADDR {0xE0100FFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SDIO1_BASEADDR {0xE0101000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SDIO1_HIGHADDR {0xE0101FFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SDIO_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SDIO_PERIPHERAL_DIVISOR0 {20} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SDIO_PERIPHERAL_FREQMHZ {50} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SDIO_PERIPHERAL_VALID {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SINGLE_QSPI_DATA_MODE {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SMC_CYCLE_T0 {NA} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SMC_CYCLE_T1 {NA} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SMC_CYCLE_T2 {NA} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SMC_CYCLE_T3 {NA} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SMC_CYCLE_T4 {NA} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SMC_CYCLE_T5 {NA} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SMC_CYCLE_T6 {NA} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SMC_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SMC_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SMC_PERIPHERAL_FREQMHZ {100} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SMC_PERIPHERAL_VALID {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI0_BASEADDR {0xE0006000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI0_GRP_SS0_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI0_GRP_SS0_IO {EMIO} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI0_GRP_SS1_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI0_GRP_SS1_IO {EMIO} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI0_GRP_SS2_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI0_GRP_SS2_IO {EMIO} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI0_HIGHADDR {0xE0006FFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI0_PERIPHERAL_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI0_SPI0_IO {EMIO} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI1_BASEADDR {0xE0007000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI1_GRP_SS0_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI1_GRP_SS0_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI1_GRP_SS1_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI1_GRP_SS1_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI1_GRP_SS2_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI1_GRP_SS2_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI1_HIGHADDR {0xE0007FFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI1_PERIPHERAL_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI1_SPI1_IO {EMIO} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI_PERIPHERAL_DIVISOR0 {6} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI_PERIPHERAL_FREQMHZ {166.666666} 
ad_ip_parameter sys_ps7 CONFIG.PCW_SPI_PERIPHERAL_VALID {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_ACP_ARUSER_VAL {31} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_ACP_AWUSER_VAL {31} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_ACP_ID_WIDTH {3} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_GP0_ID_WIDTH {6} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_GP1_ID_WIDTH {6} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_HP0_DATA_WIDTH {64} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_HP0_ID_WIDTH {6} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_HP1_DATA_WIDTH {64} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_HP1_ID_WIDTH {6} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_HP2_DATA_WIDTH {64} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_HP2_ID_WIDTH {6} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_HP3_DATA_WIDTH {64} 
ad_ip_parameter sys_ps7 CONFIG.PCW_S_AXI_HP3_ID_WIDTH {6} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TPIU_PERIPHERAL_CLKSRC {External} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TPIU_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TPIU_PERIPHERAL_FREQMHZ {200} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_BUFFER_CLOCK_DELAY {12} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_BUFFER_FIFO_SIZE {128} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_GRP_16BIT_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_GRP_16BIT_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_GRP_2BIT_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_GRP_2BIT_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_GRP_32BIT_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_GRP_32BIT_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_GRP_4BIT_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_GRP_4BIT_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_GRP_8BIT_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_GRP_8BIT_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_INTERNAL_WIDTH {2} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_PIPELINE_WIDTH {8} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TRACE_TRACE_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_BASEADDR {0xE0104000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_CLK0_PERIPHERAL_CLKSRC {CPU_1X} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_CLK0_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_CLK0_PERIPHERAL_FREQMHZ {133.333333} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_CLK1_PERIPHERAL_CLKSRC {CPU_1X} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_CLK1_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_CLK1_PERIPHERAL_FREQMHZ {133.333333} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_CLK2_PERIPHERAL_CLKSRC {CPU_1X} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_CLK2_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_CLK2_PERIPHERAL_FREQMHZ {133.333333} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_HIGHADDR {0xE0104fff} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC0_TTC0_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_BASEADDR {0xE0105000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_CLK0_PERIPHERAL_CLKSRC {CPU_1X} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_CLK0_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_CLK0_PERIPHERAL_FREQMHZ {133.333333} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_CLK1_PERIPHERAL_CLKSRC {CPU_1X} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_CLK1_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_CLK1_PERIPHERAL_FREQMHZ {133.333333} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_CLK2_PERIPHERAL_CLKSRC {CPU_1X} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_CLK2_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_CLK2_PERIPHERAL_FREQMHZ {133.333333} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_HIGHADDR {0xE0105fff} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC1_TTC1_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_TTC_PERIPHERAL_FREQMHZ {50} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART0_BASEADDR {0xE0000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART0_BAUD_RATE {115200} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART0_GRP_FULL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART0_GRP_FULL_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART0_HIGHADDR {0xE0000FFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART0_PERIPHERAL_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART0_UART0_IO {MIO 14 .. 15} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART1_BASEADDR {0xE0001000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART1_BAUD_RATE {921600} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART1_GRP_FULL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART1_GRP_FULL_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART1_HIGHADDR {0xE0001FFF} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART1_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART1_UART1_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART_PERIPHERAL_CLKSRC {IO PLL} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART_PERIPHERAL_DIVISOR0 {10} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART_PERIPHERAL_FREQMHZ {100} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UART_PERIPHERAL_VALID {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_ACT_DDR_FREQ_MHZ {525.000000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_ADV_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_AL {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_BANK_ADDR_COUNT {3} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_BL {8} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY0 {0.223} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY1 {0.212} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY2 {0.085} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY3 {0.092} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_BUS_WIDTH {16 Bit} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CL {7} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_0_LENGTH_MM {25.8} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PACKAGE_LENGTH {80.4535} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PROPOGATION_DELAY {160} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_1_LENGTH_MM {25.8} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PACKAGE_LENGTH {80.4535} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PROPOGATION_DELAY {160} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_2_LENGTH_MM {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PACKAGE_LENGTH {80.4535} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PROPOGATION_DELAY {160} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_3_LENGTH_MM {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PACKAGE_LENGTH {80.4535} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PROPOGATION_DELAY {160} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CLOCK_STOP_EN {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_COL_ADDR_COUNT {10} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_CWL {6} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DEVICE_CAPACITY {4096 MBits} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_0_LENGTH_MM {15.6} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_0_PACKAGE_LENGTH {105.056} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_0_PROPOGATION_DELAY {160} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_1_LENGTH_MM {18.8} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_1_PACKAGE_LENGTH {66.904} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_1_PROPOGATION_DELAY {160} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_2_LENGTH_MM {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_2_PACKAGE_LENGTH {89.1715} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_2_PROPOGATION_DELAY {160} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_3_LENGTH_MM {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_3_PACKAGE_LENGTH {113.63} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_3_PROPOGATION_DELAY {160} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 {0.040} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 {0.058} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2 {-0.009} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3 {-0.033} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQ_0_LENGTH_MM {16.5} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQ_0_PACKAGE_LENGTH {98.503} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQ_0_PROPOGATION_DELAY {160} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQ_1_LENGTH_MM {18} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQ_1_PACKAGE_LENGTH {68.5855} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQ_1_PROPOGATION_DELAY {160} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQ_2_LENGTH_MM {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQ_2_PACKAGE_LENGTH {90.295} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQ_2_PROPOGATION_DELAY {160} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQ_3_LENGTH_MM {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQ_3_PACKAGE_LENGTH {103.977} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DQ_3_PROPOGATION_DELAY {160} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_DRAM_WIDTH {16 Bits} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_ECC {Disabled} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_FREQ_MHZ {525} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_HIGH_TEMP {Normal (0-85)} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_MEMORY_TYPE {DDR 3} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_PARTNO {MT41K256M16 RE-125} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_ROW_ADDR_COUNT {15} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_SPEED_BIN {DDR3_1066F} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_TRAIN_DATA_EYE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_TRAIN_READ_GATE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_TRAIN_WRITE_LEVEL {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_T_FAW {40.0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_T_RAS_MIN {35.0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_T_RC {48.75} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_T_RCD {7} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_T_RP {7} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_DDR_USE_INTERNAL_VREF {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_UIPARAM_GENERATE_SUMMARY {NA} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB0_BASEADDR {0xE0102000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB0_HIGHADDR {0xE0102fff} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB0_PERIPHERAL_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB0_PERIPHERAL_FREQMHZ {60} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB0_RESET_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB0_RESET_IO {MIO 46} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB0_USB0_IO {MIO 28 .. 39} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB1_BASEADDR {0xE0103000} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB1_HIGHADDR {0xE0103fff} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB1_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB1_PERIPHERAL_FREQMHZ {60} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB1_RESET_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB1_RESET_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB1_USB1_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB_RESET_ENABLE {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB_RESET_POLARITY {Active Low} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USB_RESET_SELECT {Share reset pin} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_AXI_FABRIC_IDLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_AXI_NONSECURE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_CORESIGHT {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_CROSS_TRIGGER {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_CR_FABRIC {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_DDR_BYPASS {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_DEBUG {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_DEFAULT_ACP_USER_VAL {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_DMA0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_DMA1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_DMA2 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_DMA3 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_EXPANDED_IOP {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_EXPANDED_PS_SLCR_REGISTERS {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_FABRIC_INTERRUPT {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_HIGH_OCM {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_M_AXI_GP0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_M_AXI_GP1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_PROC_EVENT_BUS {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_PS_SLCR_REGISTERS {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_S_AXI_ACP {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_S_AXI_GP0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_S_AXI_GP1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_S_AXI_HP0 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_S_AXI_HP1 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_S_AXI_HP2 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_S_AXI_HP3 {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_TRACE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_USE_TRACE_DATA_EDGE_DETECTOR {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_VALUE_SILVERSION {3} 
ad_ip_parameter sys_ps7 CONFIG.PCW_WDT_PERIPHERAL_CLKSRC {CPU_1X} 
ad_ip_parameter sys_ps7 CONFIG.PCW_WDT_PERIPHERAL_DIVISOR0 {1} 
ad_ip_parameter sys_ps7 CONFIG.PCW_WDT_PERIPHERAL_ENABLE {0} 
ad_ip_parameter sys_ps7 CONFIG.PCW_WDT_PERIPHERAL_FREQMHZ {133.333333} 
ad_ip_parameter sys_ps7 CONFIG.PCW_WDT_WDT_IO {<Select>} 
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_0_PULLUP                              {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_1_PULLUP                              {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_9_PULLUP                              {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_10_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_11_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_12_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_13_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_14_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_15_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_16_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_17_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_18_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_19_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_20_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_21_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_22_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_23_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_24_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_25_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_26_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_27_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_28_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_29_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_30_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_31_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_32_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_33_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_34_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_35_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_36_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_37_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_38_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_39_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_40_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_41_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_42_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_43_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_44_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_45_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_46_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_47_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_48_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_49_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_50_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_51_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_52_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_53_PULLUP                             {disabled}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_0_SLEW                                {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_1_SLEW                                {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_2_SLEW                                {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_3_SLEW                                {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_4_SLEW                                {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_5_SLEW                                {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_6_SLEW                                {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_7_SLEW                                {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_8_SLEW                                {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_9_SLEW                                {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_10_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_11_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_12_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_13_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_14_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_15_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_16_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_17_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_18_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_19_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_20_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_21_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_22_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_23_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_24_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_25_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_26_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_27_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_28_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_29_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_30_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_31_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_32_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_33_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_34_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_35_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_36_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_37_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_38_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_39_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_40_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_41_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_42_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_43_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_44_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_45_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_46_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_47_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_48_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_49_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_50_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_51_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_52_SLEW                               {slow}
ad_ip_parameter sys_ps7 CONFIG.PCW_MIO_53_SLEW                               {slow}
