####################################################################################
## Copyright (c) 2018 - 2026 Analog Devices, Inc.
### SPDX short identifier: BSD-1-Clause
####################################################################################

include ../scripts/project-toplevel.mk
