###############################################################################
## Copyright (C) 2025 Analog Devices, Inc. All rights reserved.
### SPDX short identifier: ADIBSD
###############################################################################

source ../../../../hdl/scripts/adi_env.tcl
source ../../../../hdl/projects/scripts/adi_project_xilinx.tcl
source ../../../../hdl/projects/scripts/adi_board.tcl

# get_env_param retrieves parameter value from the environment if exists,
# other case use the default value
#
#   Use over-writable parameters from the environment.
#
#    e.g.
#    ID=11+  make JESD_MODE=64B66B RX_LANE_RATE=26.4 TX_LANE_RATE=26.4 RX_B_LANE_RATE=26.4 TX_B_LANE_RATE=26.4
#    ID=47   make JESD_MODE=64B66B RX_LANE_RATE=10.3125 TX_LANE_RATE=10.3125 RX_JESD_M=4 TX_JESD_M=4 RX_JESD_L=8  TX_JESD_L=8  RX_JESD_S=1 TX_JESD_S=1 RX_JESD_NP=16 TX_JESD_NP=16 RX_B_LANE_RATE=10.3125 TX_B_LANE_RATE=10.3125 RX_B_JESD_M=4 TX_B_JESD_M=4 RX_B_JESD_L=8  TX_B_JESD_L=8  RX_B_JESD_S=1 TX_B_JESD_S=1 RX_B_JESD_NP=16 TX_B_JESD_NP=16
#    ID=47+  make JESD_MODE=64B66B RX_LANE_RATE=20.6250 TX_LANE_RATE=20.6250 RX_JESD_M=4 TX_JESD_M=4 RX_JESD_L=8  TX_JESD_L=8  RX_JESD_S=1 TX_JESD_S=1 RX_JESD_NP=16 TX_JESD_NP=16 RX_B_LANE_RATE=20.6250 TX_B_LANE_RATE=20.625 RX_B_JESD_M=4 TX_B_JESD_M=4 RX_B_JESD_L=8  TX_B_JESD_L=8  RX_B_JESD_S=1 TX_B_JESD_S=1 RX_B_JESD_NP=16 TX_B_JESD_NP=16
#    ID=68   make JESD_MODE=64B66B RX_LANE_RATE=20.6250 TX_LANE_RATE=20.6250 RX_JESD_M=1 TX_JESD_M=1 RX_JESD_L=12 TX_JESD_L=12 RX_JESD_S=8 TX_JESD_S=8 RX_JESD_NP=12 TX_JESD_NP=12 RX_B_LANE_RATE=20.6250 TX_B_LANE_RATE=20.625 RX_B_JESD_M=1 TX_B_JESD_M=1 RX_B_JESD_L=12 TX_B_JESD_L=12 RX_B_JESD_S=8 TX_B_JESD_S=8 RX_B_JESD_NP=12 TX_B_JESD_NP=12

#
# Parameter description:
#   JESD_MODE : Used link layer encoder mode
#      64B66B - 64b66b link layer defined in JESD 204C
#      8B10B  - 8b10b link layer defined in JESD 204B
#
#   RX_LANE_RATE :  Lane rate of the Rx link ( Apollo to FPGA )
#   TX_LANE_RATE :  Lane rate of the Tx link ( FPGA to Apollo )
#   [RX/TX]_JESD_M : Number of converters per link
#   [RX/TX]_JESD_L : Number of lanes per link
#   [RX/TX]_JESD_NP : Number of bits per sample
#   [RX/TX]_NUM_LINKS : Number of links - only when ASYMMETRIC_A_B_MODE = 0
#   [RX/TX]_KS_PER_CHANNEL: Number of samples stored in internal buffers in kilosamples per converter (M)
#   ASYMMETRIC_A_B_MODE : When set, each Apollo side has its own JESD link
#   RX_B_LANE_RATE :  Lane rate of the Rx link ( Apollo to FPGA ) for B side
#   TX_B_LANE_RATE :  Lane rate of the Tx link ( FPGA to Apollo ) for B side
#   [RX/TX]_B_JESD_M : Number of converters per link for B side
#   [RX/TX]_B_JESD_L : Number of lanes per link for B side
#   [RX/TX]_B_JESD_NP : Number of bits per sample for B side
#   [RX/TX]_B_KS_PER_CHANNEL: Number of samples stored in internal buffers in kilosamples per converter (M) for B side
#

adi_project ad9084_fmca_ebz_vcu118 0 [list \
  JESD_MODE           [get_env_param JESD_MODE       64B66B ] \
  RX_LANE_RATE        [get_env_param RX_LANE_RATE    20.625 ] \
  TX_LANE_RATE        [get_env_param TX_LANE_RATE    20.625 ] \
  RX_JESD_M           [get_env_param RX_JESD_M            4 ] \
  RX_JESD_L           [get_env_param RX_JESD_L            8 ] \
  RX_JESD_S           [get_env_param RX_JESD_S            1 ] \
  RX_JESD_NP          [get_env_param RX_JESD_NP          16 ] \
  RX_NUM_LINKS        [get_env_param RX_NUM_LINKS         1 ] \
  TX_JESD_M           [get_env_param TX_JESD_M            4 ] \
  TX_JESD_L           [get_env_param TX_JESD_L            8 ] \
  TX_JESD_S           [get_env_param TX_JESD_S            1 ] \
  TX_JESD_NP          [get_env_param TX_JESD_NP          16 ] \
  TX_NUM_LINKS        [get_env_param TX_NUM_LINKS         1 ] \
  RX_KS_PER_CHANNEL   [get_env_param RX_KS_PER_CHANNEL   32 ] \
  TX_KS_PER_CHANNEL   [get_env_param TX_KS_PER_CHANNEL   32 ] \
  ASYMMETRIC_A_B_MODE [get_env_param ASYMMETRIC_A_B_MODE  1 ] \
  RX_B_LANE_RATE      [get_env_param RX_B_LANE_RATE  20.625 ] \
  TX_B_LANE_RATE      [get_env_param TX_B_LANE_RATE  20.625 ] \
  RX_B_JESD_M         [get_env_param RX_B_JESD_M          4 ] \
  RX_B_JESD_L         [get_env_param RX_B_JESD_L          8 ] \
  RX_B_JESD_S         [get_env_param RX_B_JESD_S          1 ] \
  RX_B_JESD_NP        [get_env_param RX_B_JESD_NP        16 ] \
  TX_B_JESD_M         [get_env_param TX_B_JESD_M          4 ] \
  TX_B_JESD_L         [get_env_param TX_B_JESD_L          8 ] \
  TX_B_JESD_S         [get_env_param TX_B_JESD_S          1 ] \
  TX_B_JESD_NP        [get_env_param TX_B_JESD_NP        16 ] \
  RX_B_KS_PER_CHANNEL [get_env_param RX_B_KS_PER_CHANNEL 32 ] \
  TX_B_KS_PER_CHANNEL [get_env_param TX_B_KS_PER_CHANNEL 32 ] \
]

adi_project_files ad9084_fmca_ebz_vcu118 [list \
  "system_top.v" \
  "system_constr.xdc"\
  "timing_constr.xdc"\
  "../common/hsci_phy_top.sv"\
  "../common/ad9084_fmca_ebz_spi.v"\
  "$ad_hdl_dir/library/common/ad_rst.v"\
  "$ad_hdl_dir/library/common/ad_iobuf.v" \
  "$ad_hdl_dir/library/xilinx/common/ad_rst_constr.xdc"\
  "$ad_hdl_dir/projects/common/vcu118/vcu118_system_constr.xdc" ]
create_ip -name high_speed_selectio_wiz -vendor xilinx.com -library ip -version 3.6 -module_name high_speed_selectio_wiz_0
set_property -dict [list CONFIG.PLL_LOCS {PLL_X0Y12 PLL_X0Y13} CONFIG.BUS_DIR {3} CONFIG.FIFO_RD_EN_CONTROL {1} CONFIG.PLL0_DATA_SPEED {1600} CONFIG.PLL0_INPUT_CLK_FREQ {200.000} CONFIG.PLL0_RX_EXTERNAL_CLK_TO_DATA {3} CONFIG.PLL0_PLLOUT0 {200.000} CONFIG.RIU_FROM_PLL {1} CONFIG.PLL0_CLK_SOURCE {BUFG_TO_PLL} CONFIG.BANK {45_(HP)} CONFIG.DIFFERENTIAL_IO_STD {LVDS} CONFIG.TX_PRE_EMPHASIS_D {FALSE} CONFIG.ENABLE_PLL_DRP_PORTS {0} CONFIG.ENABLE_N_PINS {0} CONFIG.BYTE0_PIN4_SIGNAL_NAME {data_out_p} CONFIG.BYTE0_PIN5_SIGNAL_NAME {data_out_n} CONFIG.BYTE0_PIN8_SIGNAL_NAME {clk_out_p} CONFIG.BYTE0_PIN9_SIGNAL_NAME {clk_out_n} CONFIG.BYTE0_PIN0_LOC {Y32} CONFIG.BYTE0_PIN1_LOC {W32} CONFIG.BYTE0_PIN2_LOC {V32} CONFIG.BYTE0_PIN3_LOC {U33} CONFIG.BYTE0_PIN4_LOC {Y34} CONFIG.BYTE0_PIN5_LOC {W34} CONFIG.BYTE0_PIN6_LOC {U35} CONFIG.BYTE0_PIN7_LOC {T36} CONFIG.BYTE0_PIN8_LOC {V33} CONFIG.BYTE0_PIN9_LOC {V34} CONFIG.BYTE0_PIN10_LOC {T34} CONFIG.BYTE0_PIN11_LOC {T35} CONFIG.BYTE0_PIN12_LOC {Y33} CONFIG.BYTE0_PIN0_NAME {IO_L1P_T0L_N0_DBC_45} CONFIG.BYTE0_PIN1_NAME {IO_L1N_T0L_N1_DBC_45} CONFIG.BYTE0_PIN2_NAME {IO_L2P_T0L_N2_45} CONFIG.BYTE0_PIN3_NAME {IO_L2N_T0L_N3_45} CONFIG.BYTE0_PIN4_NAME {IO_L3P_T0L_N4_AD15P_45} CONFIG.BYTE0_PIN5_NAME {IO_L3N_T0L_N5_AD15N_45} CONFIG.BYTE0_PIN6_NAME {IO_L4P_T0U_N6_DBC_AD7P_45} CONFIG.BYTE0_PIN7_NAME {IO_L4N_T0U_N7_DBC_AD7N_45} CONFIG.BYTE0_PIN8_NAME {IO_L5P_T0U_N8_AD14P_45} CONFIG.BYTE0_PIN9_NAME {IO_L5N_T0U_N9_AD14N_45} CONFIG.BYTE0_PIN10_NAME {IO_L6P_T0U_N10_AD6P_45} CONFIG.BYTE0_PIN11_NAME {IO_L6N_T0U_N11_AD6N_45} CONFIG.BYTE0_PIN12_NAME {IO_T0U_N12_VRP_45} CONFIG.BYTE0_PIN4_BUS_DIR {TX} CONFIG.BYTE0_PIN5_BUS_DIR {TX} CONFIG.BYTE0_PIN8_BUS_DIR {TX} CONFIG.BYTE0_PIN9_BUS_DIR {TX} CONFIG.BYTE0_PIN8_DATA_STROBE {Clk Fwd} CONFIG.BYTE0_PIN9_DATA_STROBE {Clk Fwd} CONFIG.BYTE0_PIN4_SIG_TYPE {DIFF} CONFIG.BYTE0_PIN5_SIG_TYPE {DIFF} CONFIG.BYTE0_PIN8_SIG_TYPE {DIFF} CONFIG.BYTE0_PIN9_SIG_TYPE {DIFF} CONFIG.ENABLE_BYTE0_PIN4 {true} CONFIG.ENABLE_BYTE0_PIN5 {true} CONFIG.ENABLE_BYTE0_PIN8 {true} CONFIG.ENABLE_BYTE0_PIN9 {true} CONFIG.BYTE1_PIN0_LOC {T30} CONFIG.BYTE1_PIN1_LOC {T31} CONFIG.BYTE1_PIN2_LOC {U31} CONFIG.BYTE1_PIN3_LOC {U32} CONFIG.BYTE1_PIN4_LOC {Y31} CONFIG.BYTE1_PIN5_LOC {W31} CONFIG.BYTE1_PIN6_LOC {R31} CONFIG.BYTE1_PIN7_LOC {P31} CONFIG.BYTE1_PIN8_LOC {R32} CONFIG.BYTE1_PIN9_LOC {P32} CONFIG.BYTE1_PIN10_LOC {T33} CONFIG.BYTE1_PIN11_LOC {R33} CONFIG.BYTE1_PIN12_LOC {V30} CONFIG.BYTE1_PIN0_NAME {IO_L7P_T1L_N0_QBC_AD13P_45} CONFIG.BYTE1_PIN1_NAME {IO_L7N_T1L_N1_QBC_AD13N_45} CONFIG.BYTE1_PIN2_NAME {IO_L8P_T1L_N2_AD5P_45} CONFIG.BYTE1_PIN3_NAME {IO_L8N_T1L_N3_AD5N_45} CONFIG.BYTE1_PIN4_NAME {IO_L9P_T1L_N4_AD12P_45} CONFIG.BYTE1_PIN5_NAME {IO_L9N_T1L_N5_AD12N_45} CONFIG.BYTE1_PIN6_NAME {IO_L10P_T1U_N6_QBC_AD4P_45} CONFIG.BYTE1_PIN7_NAME {IO_L10N_T1U_N7_QBC_AD4N_45} CONFIG.BYTE1_PIN8_NAME {IO_L11P_T1U_N8_GC_45} CONFIG.BYTE1_PIN9_NAME {IO_L11N_T1U_N9_GC_45} CONFIG.BYTE1_PIN10_NAME {IO_L12P_T1U_N10_GC_45} CONFIG.BYTE1_PIN11_NAME {IO_L12N_T1U_N11_GC_45} CONFIG.BYTE1_PIN12_NAME {IO_T1U_N12_45} CONFIG.ENABLE_BYTE2_PIN0 {false} CONFIG.ENABLE_BYTE2_PIN6 {true} CONFIG.ENABLE_BYTE2_PIN7 {true} CONFIG.ENABLE_BYTE2_PIN8 {true} CONFIG.ENABLE_BYTE2_PIN9 {true} CONFIG.BYTE2_PIN6_SIG_TYPE {DIFF} CONFIG.BYTE2_PIN7_SIG_TYPE {DIFF} CONFIG.BYTE2_PIN8_SIG_TYPE {DIFF} CONFIG.BYTE2_PIN9_SIG_TYPE {DIFF} CONFIG.BYTE2_PIN0_DATA_STROBE {Data} CONFIG.BYTE2_PIN6_DATA_STROBE {Strobe} CONFIG.BYTE2_PIN7_DATA_STROBE {Strobe} CONFIG.BYTE2_PIN6_SIGNAL_NAME {clk_in_p} CONFIG.BYTE2_PIN7_SIGNAL_NAME {clk_in_n} CONFIG.BYTE2_PIN8_SIGNAL_NAME {data_in_p} CONFIG.BYTE2_PIN9_SIGNAL_NAME {data_in_n} CONFIG.BYTE2_PIN0_LOC {R34} CONFIG.BYTE2_PIN1_LOC {P34} CONFIG.BYTE2_PIN2_LOC {P35} CONFIG.BYTE2_PIN3_LOC {P36} CONFIG.BYTE2_PIN4_LOC {M37} CONFIG.BYTE2_PIN5_LOC {L38} CONFIG.BYTE2_PIN6_LOC {P37} CONFIG.BYTE2_PIN7_LOC {N37} CONFIG.BYTE2_PIN8_LOC {M36} CONFIG.BYTE2_PIN9_LOC {L36} CONFIG.BYTE2_PIN10_LOC {N38} CONFIG.BYTE2_PIN11_LOC {M38} CONFIG.BYTE2_PIN12_LOC {R36} CONFIG.BYTE2_PIN0_NAME {IO_L13P_T2L_N0_GC_QBC_45} CONFIG.BYTE2_PIN1_NAME {IO_L13N_T2L_N1_GC_QBC_45} CONFIG.BYTE2_PIN2_NAME {IO_L14P_T2L_N2_GC_45} CONFIG.BYTE2_PIN3_NAME {IO_L14N_T2L_N3_GC_45} CONFIG.BYTE2_PIN4_NAME {IO_L15P_T2L_N4_AD11P_45} CONFIG.BYTE2_PIN5_NAME {IO_L15N_T2L_N5_AD11N_45} CONFIG.BYTE2_PIN6_NAME {IO_L16P_T2U_N6_QBC_AD3P_45} CONFIG.BYTE2_PIN7_NAME {IO_L16N_T2U_N7_QBC_AD3N_45} CONFIG.BYTE2_PIN8_NAME {IO_L17P_T2U_N8_AD10P_45} CONFIG.BYTE2_PIN9_NAME {IO_L17N_T2U_N9_AD10N_45} CONFIG.BYTE2_PIN10_NAME {IO_L18P_T2U_N10_AD2P_45} CONFIG.BYTE2_PIN11_NAME {IO_L18N_T2U_N11_AD2N_45} CONFIG.BYTE2_PIN12_NAME {IO_T2U_N12_45} CONFIG.ENABLE_BYTE3_PIN12 {false} CONFIG.BYTE3_PIN0_LOC {L34} CONFIG.BYTE3_PIN1_LOC {K34} CONFIG.BYTE3_PIN2_LOC {N34} CONFIG.BYTE3_PIN3_LOC {N35} CONFIG.BYTE3_PIN4_LOC {L33} CONFIG.BYTE3_PIN5_LOC {K33} CONFIG.BYTE3_PIN6_LOC {N33} CONFIG.BYTE3_PIN7_LOC {M33} CONFIG.BYTE3_PIN8_LOC {N32} CONFIG.BYTE3_PIN9_LOC {M32} CONFIG.BYTE3_PIN10_LOC {M35} CONFIG.BYTE3_PIN11_LOC {L35} CONFIG.BYTE3_PIN12_LOC {K36} CONFIG.BYTE3_PIN0_NAME {IO_L19P_T3L_N0_DBC_AD9P_45} CONFIG.BYTE3_PIN1_NAME {IO_L19N_T3L_N1_DBC_AD9N_45} CONFIG.BYTE3_PIN2_NAME {IO_L20P_T3L_N2_AD1P_45} CONFIG.BYTE3_PIN3_NAME {IO_L20N_T3L_N3_AD1N_45} CONFIG.BYTE3_PIN4_NAME {IO_L21P_T3L_N4_AD8P_45} CONFIG.BYTE3_PIN5_NAME {IO_L21N_T3L_N5_AD8N_45} CONFIG.BYTE3_PIN6_NAME {IO_L22P_T3U_N6_DBC_AD0P_45} CONFIG.BYTE3_PIN7_NAME {IO_L22N_T3U_N7_DBC_AD0N_45} CONFIG.BYTE3_PIN8_NAME {IO_L23P_T3U_N8_45} CONFIG.BYTE3_PIN9_NAME {IO_L23N_T3U_N9_45} CONFIG.BYTE3_PIN10_NAME {IO_L24P_T3U_N10_45} CONFIG.BYTE3_PIN11_NAME {IO_L24N_T3U_N11_45} CONFIG.BYTE3_PIN12_NAME {IO_T3U_N12_45} CONFIG.BYTE0_PIN5_INIT {1} CONFIG.BYTE0_PIN9_INIT {1} CONFIG.APPEND_PIN_NO {0}] [get_ips high_speed_selectio_wiz_0]

generate_target {instantiation_template} [get_files ./ad9084_fmca_ebz_vcu118.srcs/sources_1/ip/high_speed_selectio_wiz_0/high_speed_selectio_wiz_0.xci]
generate_target all [get_files ./ad9084_fmca_ebz_vcu118.srcs/sources_1/ip/high_speed_selectio_wiz_0/high_speed_selectio_wiz_0.xci]


# Avoid critical warning in OOC mode from the clock definitions
# since at that stage the submodules are not stiched together yet
if {$ADI_USE_OOC_SYNTHESIS == 1} {
  set_property used_in_synthesis false [get_files timing_constr.xdc]
}

set_property strategy Performance_RefinePlacement [get_runs impl_1]

adi_project_run ad9084_fmca_ebz_vcu118
