
source ../../scripts/adi_env.tcl
source $ad_hdl_dir/projects/scripts/adi_project.tcl

adi_project_create fmcomms2_ml605
adi_project_files fmcomms2_ml605 [list \
  "$ad_hdl_dir/library/common/ad_rst.v" \
  "$ad_hdl_dir/library/common/ad_mul_u16.v" \
  "$ad_hdl_dir/library/common/ad_dds_sine.v" \
  "$ad_hdl_dir/library/common/ad_dds_1.v" \
  "$ad_hdl_dir/library/common/ad_dds.v" \
  "$ad_hdl_dir/library/common/ad_datafmt.v" \
  "$ad_hdl_dir/library/common/ad_dcfilter.v" \
  "$ad_hdl_dir/library/common/ad_iqcor.v" \
  "$ad_hdl_dir/library/common/up_axi.v" \
  "$ad_hdl_dir/library/common/up_xfer_cntrl.v" \
  "$ad_hdl_dir/library/common/up_xfer_status.v" \
  "$ad_hdl_dir/library/common/up_clock_mon.v" \
  "$ad_hdl_dir/library/common/up_delay_cntrl.v" \
  "$ad_hdl_dir/library/common/up_drp_cntrl.v" \
  "$ad_hdl_dir/library/common/up_adc_common.v" \
  "$ad_hdl_dir/library/common/up_adc_channel.v" \
  "$ad_hdl_dir/library/common/up_dac_common.v" \
  "$ad_hdl_dir/library/common/up_dac_channel.v" \
  "$ad_hdl_dir/library/axi_ad9361/axi_ad9361_dev_if.v" \
  "$ad_hdl_dir/library/axi_ad9361/axi_ad9361_pnlb.v" \
  "$ad_hdl_dir/library/axi_ad9361/axi_ad9361_rx_pnmon.v" \
  "$ad_hdl_dir/library/axi_ad9361/axi_ad9361_rx_channel.v" \
  "$ad_hdl_dir/library/axi_ad9361/axi_ad9361_rx.v" \
  "$ad_hdl_dir/library/axi_ad9361/axi_ad9361_tx_dds.v" \
  "$ad_hdl_dir/library/axi_ad9361/axi_ad9361_tx_channel.v" \
  "$ad_hdl_dir/library/axi_ad9361/axi_ad9361_tx.v" \
  "$ad_hdl_dir/library/axi_ad9361/axi_ad9361.v" \
  "$ad_hdl_dir/library/common/sync_bits.v" \
  "$ad_hdl_dir/library/common/sync_gray.v" \
  "$ad_hdl_dir/library/axi_fifo/axi_fifo.v" \
  "$ad_hdl_dir/library/axi_fifo/address_gray.v" \
  "$ad_hdl_dir/library/axi_fifo/address_gray_pipelined.v" \
  "$ad_hdl_dir/library/axi_dmac/address_generator.v" \
  "$ad_hdl_dir/library/axi_dmac/data_mover.v" \
  "$ad_hdl_dir/library/axi_dmac/request_arb.v" \
  "$ad_hdl_dir/library/axi_dmac/request_generator.v" \
  "$ad_hdl_dir/library/axi_dmac/response_handler.v" \
  "$ad_hdl_dir/library/axi_dmac/axi_register_slice.v" \
  "$ad_hdl_dir/library/axi_dmac/2d_transfer.v" \
  "$ad_hdl_dir/library/axi_dmac/dest_axi_mm.v" \
  "$ad_hdl_dir/library/axi_dmac/dest_axi_stream.v" \
  "$ad_hdl_dir/library/axi_dmac/dest_fifo_inf.v" \
  "$ad_hdl_dir/library/axi_dmac/src_axi_mm.v" \
  "$ad_hdl_dir/library/axi_dmac/src_axi_stream.v" \
  "$ad_hdl_dir/library/axi_dmac/src_fifo_inf.v" \
  "$ad_hdl_dir/library/axi_dmac/splitter.v" \
  "$ad_hdl_dir/library/axi_dmac/response_generator.v" \
  "$ad_hdl_dir/library/axi_dmac/axi_dmac.v" \
  "$ad_hdl_dir/library/axi_dmac/axi_repack.v" \
  "system_constr.ucf" \
  "system_top.v" ]

adi_project_run fmcomms2_ml605

