FROM registry.gitlab.com/islandoftex/images/texlive:TL2022-2022-12-25-full

SHELL ["/bin/bash", "-c"]

ENV HOME /root

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Bucharest

ENV PROJ hdl-docs

RUN apt-get update

RUN apt-get -y --no-install-recommends install \
    python3 python3-venv python3-pip

# To convert svg to pdf, used in sphinx->LaTeX->pdf pipeline
RUN apt-get -y --no-install-recommends install \
    librsvg2-bin

RUN python3 -m venv /opt/venv

COPY requirements.txt .

RUN source /opt/venv/bin/activate ; \
    pip3 install -U pip

RUN source /opt/venv/bin/activate ; \
    pip3 install wheel vext vext.gi

RUN source /opt/venv/bin/activate ; \
    pip3 install -r requirements.txt ; \
    deactivate

RUN mkdir -p /usr/local/bin ; \
    ln -s /opt/venv/bin/symbolator /usr/local/bin/symbolator
