#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_

#define STDOUT_IS_PS7_UART
#define UART_DEVICE_ID 0

#define XPAR_GPIO_0_BASEADDR XPAR_AXI_GPIO_ADI_0_BASEADDR
#define XPAR_XGPIO_NUM_INSTANCES 1
#define XPAR_GPIO_0_DEVICE_ID 0
#define	XPAR_GPIO_0_INTERRUPT_PRESENT 1
#define	XPAR_GPIO_0_IS_DUAL 0








#endif
