on:
  workflow_call:
    outputs:
      projects:
        value: ${{ jobs.context.outputs.projects }}
    secrets:
      XILINXD_LICENSE_FILE:
        required: false
      LM_LICENSE_FILE:
        required: false

jobs:
  context:
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    permissions:
      contents: read
    outputs:
      projects: ${{ steps.context.outputs.projects }}
    env:
      XILINXD_LICENSE_FILE: ${{ secrets.XILINXD_LICENSE_FILE }}
      LM_LICENSE_FILE: ${{ secrets.LM_LICENSE_FILE }}

    steps:
    - uses: analogdevicesinc/doctools/changed-files@action
      id: state
    - uses: actions/checkout@v7

    - name: Get projects to build
      id: context
      env:
        changed_files: ${{ steps.state.outputs.changed_files }}
      run: |
        [[ -n "$XILINXD_LICENSE_FILE" ]] || export NO_AMD_XILINX=true
        [[ -n "$LM_LICENSE_FILE" ]] || export NO_ALTERA=true
        export NO_LATTICE=true
        changed_files="library/spi_engine/axi_spi_engine/axi_spi_engine.v
        library/i3c_controller/i3c_controller_host_interface/i3c_controller_host_interface_constr.ttcl"
        projects=$(echo "$changed_files" | python3 .github/scripts/changed_files_to_projects.py)
        [[ -n "$projects" ]] && {
          echo "projects=$projects" >> $GITHUB_OUTPUT
          echo "::notice ::Got projects $projects."
        } || echo "::warning ::Got not project for changed files."


