name: HDL build

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  context:
    uses: ./.github/workflows/context.yml
    if: (github.event_name != 'push' || github.repository_owner == 'analogdevicesinc')
    permissions:
      contents: read
    secrets:
      XILINXD_LICENSE_FILE: ${{ secrets.XILINXD_LICENSE_FILE }}
      LM_LICENSE_FILE: ${{ secrets.LM_LICENSE_FILE }}
  build:
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.context.outputs.projects) }}
    uses: ./.github/workflows/build.yml
    needs: [ context ]
    permissions:
      contents: read
    secrets:
      XILINXD_LICENSE_FILE: ${{ secrets.XILINXD_LICENSE_FILE }}
      LM_LICENSE_FILE: ${{ secrets.LM_LICENSE_FILE }}
    with:
      project: ${{ matrix.project }}
