set_property -dict {PACKAGE_PIN AG14 IOSTANDARD LVCMOS33 } [get_ports tdd_out[0] ]
set_property -dict {PACKAGE_PIN AF13 IOSTANDARD LVCMOS33 } [get_ports tdd_out[1] ]
set_property -dict {PACKAGE_PIN AE13 IOSTANDARD LVCMOS33 } [get_ports tdd_out[2] ]
set_property -dict {PACKAGE_PIN AJ14 IOSTANDARD LVCMOS33 } [get_ports tdd_out[3] ]
set_property -dict {PACKAGE_PIN AJ15 IOSTANDARD LVCMOS33 } [get_ports tdd_out[4] ]
set_property -dict {PACKAGE_PIN AH13 IOSTANDARD LVCMOS33 } [get_ports tdd_out[5] ]
set_property -dict {PACKAGE_PIN AH14 IOSTANDARD LVCMOS33 } [get_ports tdd_out[6] ]
set_property -dict {PACKAGE_PIN AL12 IOSTANDARD LVCMOS33 } [get_ports tdd_out[7] ]
